import { Station } from '../stations';

export const POLICE: Station = {
    title: 'Police',
    hash: '8a388107cdf3934b3f7a3f1e2b33199c',
    tracks: [
        { title: 'Clip 1' }, { title: 'Clip 2' }, { title: 'Clip 3' },
        { title: 'Clip 4' }, { title: 'Clip 5' }, { title: 'Clip 6' },
        { title: 'Clip 7' }, { title: 'Clip 8' }, { title: 'Clip 9' },
        { title: 'Clip 10' }, { title: 'Clip 11' }, { title: 'Clip 12' },
        { title: 'Clip 13' }, { title: 'Clip 14' }, { title: 'Clip 15' },
        { title: 'Clip 16' }, { title: 'Clip 17' }, { title: 'Clip 18' },
        { title: 'Clip 19' }, { title: 'Clip 20' }, { title: 'Clip 21' },
        { title: 'Clip 22' }, { title: 'Clip 23' }, { title: 'Clip 24' },
        { title: 'Clip 25' }, { title: 'Clip 26' }, { title: 'Clip 27' },
        { title: 'Clip 28' }, { title: 'Clip 29' }, { title: 'Clip 30' },
        { title: 'Clip 31' }, { title: 'Clip 32' }, { title: 'Clip 33' },
        { title: 'Clip 34' }, { title: 'Clip 35' }, { title: 'Clip 36' },
        { title: 'Clip 37' }, { title: 'Clip 38' }, { title: 'Clip 39' },
        { title: 'Clip 40' }, { title: 'Clip 41' }, { title: 'Clip 42' },
        { title: 'Clip 43' }, { title: 'Clip 44' }, { title: 'Clip 45' },
        { title: 'Clip 46' }, { title: 'Clip 47' }, { title: 'Clip 48' },
        { title: 'Clip 49' }, { title: 'Clip 50' }, { title: 'Clip 51' },
        { title: 'Clip 52' }, { title: 'Clip 53' }, { title: 'Clip 54' },
        { title: 'Clip 55' }, { title: 'Clip 56' }, { title: 'Clip 57' },
        { title: 'Clip 58' }, { title: 'Clip 59' }, { title: 'Clip 60' },
        { title: 'Clip 61' }, { title: 'Clip 62' }, { title: 'Clip 63' },
        { title: 'Clip 64' }, { title: 'Clip 65' }, { title: 'Clip 66' },
    ],
};
