import { Station } from '../stations';

export const ADVERTS: Station = {
    title: 'Adverts',
    hash: '9b7310981c3e88d2d9eda9b18b443f75',
    tracks: [
        { title: 'Ammunation' },
        { title: "Don't let your children ride bicycles" },
        { title: "Blotto's" },
        { title: "Blotto's" },
        { title: 'Bouche cologne' },
        { title: 'Castradon' },
        { title: 'Commando pest eradication' },
        { title: 'Commemorative miniatures' },
        { title: 'The crazy cup' },
        { title: 'Creative plastic surgery' },
        { title: 'Eris shoes' },
        { title: 'Hampshire nannies ltd' },
        { title: 'The military' },
        { title: 'Logger beer' },
        { title: 'Logger light' },
        { title: 'The midlife crisis center' },
        { title: '"My five uncles" on LSBC' },
        { title: 'Proposition 421 (smoking ban)' },
        { title: 'Proposition 832 (green cards for illegal aliens)' },
        { title: 'Redwood cigarettes' },
        { title: 'Renegade cologne' },
        { title: 'Sooth' },
        { title: 'San Andreas telephone' },
        { title: 'San Andreas telephone' },
        { title: 'San Andreas telephone' },
        { title: 'San Andreas telephone' },
        { title: 'Ultimate disc in the dark' },
        { title: 'Fokari film' },
        { title: 'Dream makers' },
        { title: 'Intergalactic wrestling championship on Weasel' },
        { title: 'Proposition 602 (driving on bus lanes)' },
        { title: 'Mike Andrews' },
        { title: 'Beagle brokerage and pawn' },
        { title: "Blotto's" },
        { title: 'Shine by Helmet shine' },
        { title: 'de Koch diamonds' },
        { title: 'Change your identity' },
        { title: 'Rapidite' },
        { title: 'Grin' },
        { title: 'Mike Andrews' },
        { title: 'Celebrate with cake' },
        { title: 'Celebrate with cake' },
        { title: 'Sprunk' },
        { title: 'Crimson executive spouse indemnity services' },
        { title: "Herr Gruber's spa" },
        { title: 'American bank of Los Santos' },
        { title: 'The cavern of sorrow' },
        { title: "Cluckin' bell" },
        { title: "Cluckin' bell" },
        { title: 'The glory hole themepark' },
        { title: 'The glory hole themepark' },
        { title: 'Inversion therapy' },
        { title: 'Kilimanjaro clothes' },
        { title: 'Kilimanjaro clothes' },
        { title: 'Casa City' },
        { title: '"Law" on Weasel' },
        { title: '"Law" on Weasel' },
        { title: '"Law" on Weasel' },
        { title: 'Starfish resort and casino' },
        { title: 'Tropicarcinoma' },
        { title: 'Zebra bar' },
        { title: 'Zebra bar' },
        { title: 'The epsilon program' },
        { title: 'The epsilon program' },
        { title: 'The epsilon program' },
        { title: 'Executive intruder extermination service' },
        { title: 'Exorbio gaming system' },
        { title: 'Lustrious' },
        { title: 'Lustrious' },
    ],
};
