import { Station } from '../stations';

export const PLAYBACK_FM: Station = {
    title: 'Playback FM',
    hash: 'a88eb0130acb81b5956e412db06ea9ce',
    alternatives: [
        { hash: '056a3c5a99fe4222f8ba9beeb98de568' },
    ],
    tracks: [
        { title: 'Earthquake' },
        { title: 'Bridges open' },
        { title: 'Bone County open' },
        { title: "Well, actually, it's CSR" },
        { title: "You're really annoying" },
        { title: 'Be educated on the sounds that brung ya' },
        { title: "You don't last a minute" },
        { title: "There's a party over here" },
        { title: 'West Coast radio suckers' },
        { title: 'Ready for your training wheels?' },
        { title: "I'll go speed of light on y'all" },
        { title: 'This goes out to my man the Iceman' },
        { title: 'Los Santos police' },
        { title: 'Ugly like yo momma' },
        { title: 'Small-minded robots' },
        { title: "Should'a paid more attention in school" },
        { title: 'Propaganda' },
        { title: 'Cavern of sorrow marathon' },
        { title: "Help ain't no charity" },
        { title: "Get back to the 'burbs you fools!" },
        { title: 'I got seven digits as it is' },
        { title: 'Evening 1' },
        { title: 'Evening 2' },
        { title: 'Morning 1' },
        { title: 'Morning 2' },
        { title: 'Night 1' },
        { title: 'Night 2' },
        { title: 'Fog 1' },
        { title: 'Fog 2' },
        { title: 'Smog' },
        { title: 'Rain 1' },
        { title: 'Rain 2' },
        { title: 'Rain 3' },
        { title: 'Sunny 1' },
        { title: 'Sunny 2' },
        { title: 'While you suckers were wearing diapers' },
        { title: 'Doper than anyone else' },
        { title: 'Drop out of that whack-ass school' },
        { title: 'Skills on the mic' },
        { title: "Givin' it to ya' straight up, homeboy!" },
        { title: 'The home of classic hiphop' },
        { title: 'The man with an opinion on everything' },
        { title: "Layin' it down old skool" },
        { title: 'Word up!' },
        { title: 'The reason you put that subwoofer in your car' },
        { title: 'Word to your mamma' },
        { artist: 'Masta Ace', title: 'Me and the biz' },
        { artist: 'Masta Ace', title: 'Me and the biz (Intro)' },
        { artist: 'Masta Ace', title: 'Me and the biz (Intro DJ 1)' },
        { artist: 'Masta Ace', title: 'Me and the biz (Intro DJ 2)' },
        { artist: 'Masta Ace', title: 'Me and the biz (Outro)' },
        { artist: 'Masta Ace', title: 'Me and the biz (Outro DJ 1)' },
        { artist: 'Masta Ace', title: 'Me and the biz (Outro DJ 2)' },
        { artist: 'Big Daddy Kane', title: 'Warm it up, Kane' },
        { artist: 'Big Daddy Kane', title: 'Warm it up, Kane (Intro)' },
        { artist: 'Big Daddy Kane', title: 'Warm it up, Kane (Intro DJ 1)' },
        { artist: 'Big Daddy Kane', title: 'Warm it up, Kane (Intro DJ 2)' },
        { artist: 'Big Daddy Kane', title: 'Warm it up, Kane (Outro)' },
        { artist: 'Big Daddy Kane', title: 'Warm it up, Kane (Outro DJ 1)' },
        { artist: 'Big Daddy Kane', title: 'Warm it up, Kane (Outro DJ 2)' },
        { artist: 'Kool G and DJ Polo', title: 'Road to the riches' },
        { artist: 'Kool G and DJ Polo', title: 'Road to the riches (Intro)' },
        { artist: 'Kool G and DJ Polo', title: 'Road to the riches (Intro DJ 1)' },
        { artist: 'Kool G and DJ Polo', title: 'Road to the riches (Intro DJ 2)' },
        { artist: 'Kool G and DJ Polo', title: 'Road to the riches (Outro)' },
        { artist: 'Kool G and DJ Polo', title: 'Road to the riches (Outro DJ 1)' },
        { artist: 'Kool G and DJ Polo', title: 'Road to the riches (Outro DJ 2)' },
        { artist: 'Public Enemy', title: 'Rebel without a pause' },
        { artist: 'Public Enemy', title: 'Rebel without a pause (Intro)' },
        { artist: 'Public Enemy', title: 'Rebel without a pause (Intro DJ 1)' },
        { artist: 'Public Enemy', title: 'Rebel without a pause (Intro DJ 2)' },
        { artist: 'Public Enemy', title: 'Rebel without a pause (Outro)' },
        { artist: 'Public Enemy', title: 'Rebel without a pause (Outro DJ 1)' },
        { artist: 'Public Enemy', title: 'Rebel without a pause (Outro DJ 2)' },
        { artist: 'Rob Base and DJ EZ Rock', title: 'It takes two' },
        { artist: 'Rob Base and DJ EZ Rock', title: 'It takes two (Intro)' },
        { artist: 'Rob Base and DJ EZ Rock', title: 'It takes two (Intro DJ 1)' },
        { artist: 'Rob Base and DJ EZ Rock', title: 'It takes two (Intro DJ 2)' },
        { artist: 'Rob Base and DJ EZ Rock', title: 'It takes two (Outro)' },
        { artist: 'Rob Base and DJ EZ Rock', title: 'It takes two (Outro DJ 1)' },
        { artist: 'Rob Base and DJ EZ Rock', title: 'It takes two (Outro DJ 2)' },
        { artist: 'Eric B and Rakim', title: 'I know you got soul' },
        { artist: 'Eric B and Rakim', title: 'I know you got soul (Intro)' },
        { artist: 'Eric B and Rakim', title: 'I know you got soul (Intro DJ 1)' },
        { artist: 'Eric B and Rakim', title: 'I know you got soul (Intro DJ 2)' },
        { artist: 'Eric B and Rakim', title: 'I know you got soul (Outro)' },
        { artist: 'Eric B and Rakim', title: 'I know you got soul (Outro DJ 1)' },
        { artist: 'Eric B and Rakim', title: 'I know you got soul (Outro DJ 2)' },
        { artist: 'Brand Nubian', title: 'Brand Nubian' },
        { artist: 'Brand Nubian', title: 'Brand Nubian (Intro)' },
        { artist: 'Brand Nubian', title: 'Brand Nubian (Intro DJ 1)' },
        { artist: 'Brand Nubian', title: 'Brand Nubian (Intro DJ 2)' },
        { artist: 'Brand Nubian', title: 'Brand Nubian (Outro)' },
        { artist: 'Brand Nubian', title: 'Brand Nubian (Outro DJ 1)' },
        { artist: 'Brand Nubian', title: 'Brand Nubian (Outro DJ 2)' },
        { artist: 'Slick Rick', title: "Children's story" },
        { artist: 'Slick Rick', title: "Children's story (Intro)" },
        { artist: 'Slick Rick', title: "Children's story (Intro DJ 1)" },
        { artist: 'Slick Rick', title: "Children's story (Intro DJ 2)" },
        { artist: 'Slick Rick', title: "Children's story (Outro)" },
        { artist: 'Slick Rick', title: "Children's story (Outro DJ 1)" },
        { artist: 'Slick Rick', title: "Children's story (Outro DJ 2)" },
        { artist: 'Gang starr', title: 'BYS' },
        { artist: 'Gang starr', title: 'BYS (Intro)' },
        { artist: 'Gang starr', title: 'BYS (Intro DJ 1)' },
        { artist: 'Gang starr', title: 'BYS (Intro DJ 2)' },
        { artist: 'Gang starr', title: 'BYS (Outro)' },
        { artist: 'Gang starr', title: 'BYS (Outro DJ 1)' },
        { artist: 'Gang starr', title: 'BYS (Outro DJ 2)' },
        { artist: 'Ultramagnetic MCs', title: 'Critical beatdown' },
        { artist: 'Ultramagnetic MCs', title: 'Critical beatdown (Intro)' },
        { artist: 'Ultramagnetic MCs', title: 'Critical beatdown (Intro DJ 1)' },
        { artist: 'Ultramagnetic MCs', title: 'Critical beatdown (Intro DJ 2)' },
        { artist: 'Ultramagnetic MCs', title: 'Critical beatdown (Outro)' },
        { artist: 'Ultramagnetic MCs', title: 'Critical beatdown (Outro DJ 1)' },
        { artist: 'Ultramagnetic MCs', title: 'Critical beatdown (Outro DJ 2)' },
        { artist: 'Biz Markie', title: 'The vapors' },
        { artist: 'Biz Markie', title: 'The vapors (Intro)' },
        { artist: 'Biz Markie', title: 'The vapors (Intro DJ 1)' },
        { artist: 'Biz Markie', title: 'The vapors (Intro DJ 2)' },
        { artist: 'Biz Markie', title: 'The vapors (Outro)' },
        { artist: 'Biz Markie', title: 'The vapors (Outro DJ 1)' },
        { artist: 'Biz Markie', title: 'The vapors (Outro DJ 2)' },
        { artist: 'Spoonie Gee', title: 'The godfather' },
        { artist: 'Spoonie Gee', title: 'The godfather (Intro)' },
        { artist: 'Spoonie Gee', title: 'The godfather (Intro DJ 1)' },
        { artist: 'Spoonie Gee', title: 'The godfather (Intro DJ 2)' },
        { artist: 'Spoonie Gee', title: 'The godfather (Outro)' },
        { artist: 'Spoonie Gee', title: 'The godfather (Outro DJ 1)' },
        { artist: 'Spoonie Gee', title: 'The godfather (Outro DJ 2)' },
    ],
};
