import { Station } from '../stations';

export const KROSE: Station = {
    title: 'KROSE',
    hash: 'c2075553325e7fe8d3d50fefff857aa7',
    tracks: [
        { title: 'Earthquake' },
        { title: 'Bridges open' },
        { title: 'Bone County open' },
        { title: 'Downstairs harmonica talents' },
        { title: 'Euthanasia is a beautiful thing' },
        { title: 'I might start to cry' },
        { title: 'Darwinism' },
        { title: 'Down south again' },
        { title: 'Latte' },
        { title: 'Belt buckles' },
        { title: 'Like the plug, but a musical version' },
        { title: 'Harmonica in my pants' },
        { title: "You know what war I'm talking about" },
        { title: 'Harmonica piece' },
        { title: 'Legs akimbo' },
        { title: 'Love everyone like myself' },
        { title: "It ain't easy raising nine kids" },
        { title: 'I am shit-faced' },
        { title: 'On the prairie' },
        { title: 'I keep moving on' },
        { title: 'Make you want to square dance' },
        { title: "It's like Kant said" },
        { title: 'Play a harmonica and sing at the same time' },
        { title: 'Wicked, evil, wealthy woman' },
        { title: 'Being faithful and cheating at the same time' },
        { title: 'Robbing shit' },
        { title: 'Weed burned down' },
        { title: 'UFOs' },
        { title: 'Police on trial' },
        { title: 'Gang warfare' },
        { title: 'Morning 1' },
        { title: 'Morning 2' },
        { title: 'Night 1' },
        { title: 'Night 2' },
        { title: 'Fog 1' },
        { title: 'Fog 2' },
        { title: 'Rain' },
        { title: 'Storm 1' },
        { title: 'Storm 2' },
        { title: 'Sunny 1' },
        { title: 'Sunny 2' },
        { title: 'Barefoot and pregnant again' },
        { title: 'All America loves a cowboy' },
        { title: 'From cow poking to cow-tipping' },
        { title: 'Invented the electric guitar' },
        { title: 'Farm animals' },
        { title: 'When love shoots you in the back' },
        { title: 'Iron horse with a drinking problem' },
        { title: 'Whistle on a lonely night' },
        { title: 'It takes a cowboy to know when to shoot' },
        { artist: 'Jerry Reed', title: 'Amos Moses' },
        { artist: 'Jerry Reed', title: 'Amos Moses (Intro)' },
        { artist: 'Jerry Reed', title: 'Amos Moses (Intro DJ 1)' },
        { artist: 'Jerry Reed', title: 'Amos Moses (Intro DJ 2)' },
        { artist: 'Jerry Reed', title: 'Amos Moses (Outro)' },
        { artist: 'Jerry Reed', title: 'Amos Moses (Outro DJ 1)' },
        { artist: 'Jerry Reed', title: 'Amos Moses (Outro DJ 2)' },
        { artist: 'Conway Twitty and Loretta Lynn', title: 'Louisiana woman, Mississippi man' },
        { artist: 'Conway Twitty and Loretta Lynn', title: 'Louisiana woman, Mississippi man (Intro)' },
        { artist: 'Conway Twitty and Loretta Lynn', title: 'Louisiana woman, Mississippi man (Intro DJ 1)' },
        { artist: 'Conway Twitty and Loretta Lynn', title: 'Louisiana woman, Mississippi man (Intro DJ 2)' },
        { artist: 'Conway Twitty and Loretta Lynn', title: 'Louisiana woman, Mississippi man (Outro)' },
        { artist: 'Conway Twitty and Loretta Lynn', title: 'Louisiana woman, Mississippi man (Outro DJ 1)' },
        { artist: 'Conway Twitty and Loretta Lynn', title: 'Louisiana woman, Mississippi man (Outro DJ 2)' },
        { artist: 'The desert rose band', title: 'One step forward' },
        { artist: 'The desert rose band', title: 'One step forward (Intro)' },
        { artist: 'The desert rose band', title: 'One step forward (Intro DJ 1)' },
        { artist: 'The desert rose band', title: 'One step forward (Intro DJ 2)' },
        { artist: 'The desert rose band', title: 'One step forward (Outro)' },
        { artist: 'The desert rose band', title: 'One step forward (Outro DJ 1)' },
        { artist: 'The desert rose band', title: 'One step forward (Outro DJ 2)' },
        { artist: 'Statler brothers', title: 'New York city' },
        { artist: 'Statler brothers', title: 'New York city (Intro)' },
        { artist: 'Statler brothers', title: 'New York city (Intro DJ 1)' },
        { artist: 'Statler brothers', title: 'New York city (Intro DJ 2)' },
        { artist: 'Statler brothers', title: 'New York city (Outro)' },
        { artist: 'Statler brothers', title: 'New York city (Outro DJ 1)' },
        { artist: 'Statler brothers', title: 'New York city (Outro DJ 2)' },
        { artist: 'Statler brothers', title: 'Bed of roses' },
        { artist: 'Statler brothers', title: 'Bed of roses (Intro)' },
        { artist: 'Statler brothers', title: 'Bed of roses (Intro DJ 1)' },
        { artist: 'Statler brothers', title: 'Bed of roses (Intro DJ 2)' },
        { artist: 'Statler brothers', title: 'Bed of roses (Outro)' },
        { artist: 'Statler brothers', title: 'Bed of roses (Outro DJ 1)' },
        { artist: 'Statler brothers', title: 'Bed of roses (Outro DJ 2)' },
        { artist: 'Asleep at the wheel', title: 'The letter that Johnny Walker read' },
        { artist: 'Asleep at the wheel', title: 'The letter that Johnny Walker read (Intro)' },
        { artist: 'Asleep at the wheel', title: 'The letter that Johnny Walker read (Intro DJ 1)' },
        { artist: 'Asleep at the wheel', title: 'The letter that Johnny Walker read (Intro DJ 2)' },
        { artist: 'Asleep at the wheel', title: 'The letter that Johnny Walker read (Outro)' },
        { artist: 'Asleep at the wheel', title: 'The letter that Johnny Walker read (Outro DJ 1)' },
        { artist: 'Asleep at the wheel', title: 'The letter that Johnny Walker read (Outro DJ 2)' },
        { artist: 'Juice Newton', title: 'Queen of hearts' },
        { artist: 'Juice Newton', title: 'Queen of hearts (Intro)' },
        { artist: 'Juice Newton', title: 'Queen of hearts (Intro DJ 1)' },
        { artist: 'Juice Newton', title: 'Queen of hearts (Intro DJ 2)' },
        { artist: 'Juice Newton', title: 'Queen of hearts (Outro)' },
        { artist: 'Juice Newton', title: 'Queen of hearts (Outro DJ 1)' },
        { artist: 'Juice Newton', title: 'Queen of hearts (Outro DJ 2)' },
        { artist: 'Hank Williams', title: "Hey good lookin'" },
        { artist: 'Hank Williams', title: "Hey good lookin' (Intro)" },
        { artist: 'Hank Williams', title: "Hey good lookin' (Intro DJ 1)" },
        { artist: 'Hank Williams', title: "Hey good lookin' (Intro DJ 2)" },
        { artist: 'Hank Williams', title: "Hey good lookin' (Outro)" },
        { artist: 'Hank Williams', title: "Hey good lookin' (Outro DJ 1)" },
        { artist: 'Hank Williams', title: "Hey good lookin' (Outro DJ 2)" },
        { artist: 'Patsy Cline', title: 'Three cigarettes in the ashtray' },
        { artist: 'Patsy Cline', title: 'Three cigarettes in the ashtray (Intro)' },
        { artist: 'Patsy Cline', title: 'Three cigarettes in the ashtray (Intro DJ 1)' },
        { artist: 'Patsy Cline', title: 'Three cigarettes in the ashtray (Intro DJ 2)' },
        { artist: 'Patsy Cline', title: 'Three cigarettes in the ashtray (Outro)' },
        { artist: 'Patsy Cline', title: 'Three cigarettes in the ashtray (Outro DJ 1)' },
        { artist: 'Patsy Cline', title: 'Three cigarettes in the ashtray (Outro DJ 2)' },
        { artist: 'Eddie Rabbit', title: 'I love a rainy night' },
        { artist: 'Eddie Rabbit', title: 'I love a rainy night (Intro)' },
        { artist: 'Eddie Rabbit', title: 'I love a rainy night (Intro DJ 1)' },
        { artist: 'Eddie Rabbit', title: 'I love a rainy night (Intro DJ 2)' },
        { artist: 'Eddie Rabbit', title: 'I love a rainy night (Outro)' },
        { artist: 'Eddie Rabbit', title: 'I love a rainy night (Outro DJ 1)' },
        { artist: 'Eddie Rabbit', title: 'I love a rainy night (Outro DJ 2)' },
        { artist: 'Willie Nelson', title: 'Crazy' },
        { artist: 'Willie Nelson', title: 'Crazy (Intro)' },
        { artist: 'Willie Nelson', title: 'Crazy (Intro DJ 1)' },
        { artist: 'Willie Nelson', title: 'Crazy (Intro DJ 2)' },
        { artist: 'Willie Nelson', title: 'Crazy (Outro)' },
        { artist: 'Willie Nelson', title: 'Crazy (Outro DJ 1)' },
        { artist: 'Willie Nelson', title: 'Crazy (Outro DJ 2)' },
        { artist: 'Mickey Gilley', title: 'Make the world go away' },
        { artist: 'Mickey Gilley', title: 'Make the world go away (Intro)' },
        { artist: 'Mickey Gilley', title: 'Make the world go away (Intro DJ 1)' },
        { artist: 'Mickey Gilley', title: 'Make the world go away (Intro DJ 2)' },
        { artist: 'Mickey Gilley', title: 'Make the world go away (Outro)' },
        { artist: 'Mickey Gilley', title: 'Make the world go away (Outro DJ 1)' },
        { artist: 'Mickey Gilley', title: 'Make the world go away (Outro DJ 2)' },
        { artist: 'Ed Bruce', title: "Mama don't let your babies grow up to be cowboys" },
        { artist: 'Ed Bruce', title: "Mama don't let your babies grow up to be cowboys (Intro)" },
        { artist: 'Ed Bruce', title: "Mama don't let your babies grow up to be cowboys (Intro DJ 1)" },
        { artist: 'Ed Bruce', title: "Mama don't let your babies grow up to be cowboys (Intro DJ 2)" },
        { artist: 'Ed Bruce', title: "Mama don't let your babies grow up to be cowboys (Outro)" },
        { artist: 'Ed Bruce', title: "Mama don't let your babies grow up to be cowboys (Outro DJ 1)" },
        { artist: 'Ed Bruce', title: "Mama don't let your babies grow up to be cowboys (Outro DJ 2)" },
        { artist: 'Merle Haggard', title: 'Always wanting you' },
        { artist: 'Merle Haggard', title: 'Always wanting you (Intro)' },
        { artist: 'Merle Haggard', title: 'Always wanting you (Intro DJ 1)' },
        { artist: 'Merle Haggard', title: 'Always wanting you (Intro DJ 2)' },
        { artist: 'Merle Haggard', title: 'Always wanting you (Outro)' },
        { artist: 'Merle Haggard', title: 'Always wanting you (Outro DJ 1)' },
        { artist: 'Merle Haggard', title: 'Always wanting you (Outro DJ 2)' },
        { artist: 'Whitey Shafer', title: 'All my exes live in Texas' },
        { artist: 'Whitey Shafer', title: 'All my exes live in Texas (Intro)' },
        { artist: 'Whitey Shafer', title: 'All my exes live in Texas (Intro DJ 1)' },
        { artist: 'Whitey Shafer', title: 'All my exes live in Texas (Intro DJ 2)' },
        { artist: 'Whitey Shafer', title: 'All my exes live in Texas (Outro)' },
        { artist: 'Whitey Shafer', title: 'All my exes live in Texas (Outro DJ 1)' },
        { artist: 'Whitey Shafer', title: 'All my exes live in Texas (Outro DJ 2)' },
    ],
};
