import { Station } from '../stations';

export const K_DST: Station = {
    title: 'K-DST',
    hash: '06a63d4222209a1d6e8ce2e7ace51956',
    alternatives: [
        { hash: '11a670213e7803872d73503873d8a479' },
    ],
    tracks: [
        { title: 'Earthquake' },
        { title: 'Bridges open' },
        { title: 'Bone County open' },
        { title: 'Two kinds of people' },
        { title: "Rock 'n' roll or classical" },
        { title: 'Whatever happened to Love fist?' },
        { title: 'Keeping the spirit of rock alive' },
        { title: 'Get to the clinic' },
        { title: "Weren't the 70's great?" },
        { title: 'Music may not be the food of love' },
        { title: '1977... What a year!' },
        { title: "I'm in hell, right" },
        { title: 'That band you were in' },
        { title: "You're so lame" },
        { title: 'I live the dream' },
        { title: 'Prosecutor busted for weed' },
        { title: 'Weed farm burned down' },
        { title: 'UFOs' },
        { title: 'Evening 1' },
        { title: 'Evening 2' },
        { title: 'Morning 1' },
        { title: 'Morning 2' },
        { title: 'Morning 3' },
        { title: 'Night 1' },
        { title: 'Night 2' },
        { title: 'Night 3' },
        { title: 'Fog 1' },
        { title: 'Fog 2' },
        { title: 'Rain 1' },
        { title: 'Rain 2' },
        { title: 'Sunny 1' },
        { title: 'Sunny 2' },
        { title: 'Songs about abusing drugs and women' },
        { title: 'Tommy "The nightmare" Smith on The Dust' },
        { title: 'The way it was meant to be enjoyed' },
        { title: 'Real rockers wear leather jackets' },
        { title: "If the police can't stop you" },
        { title: "If the police can't stop you" },
        { title: 'K-DST: The Dust' },
        { title: 'Gone to rehab' },
        { title: 'Ashes to ashes, Dust to Dust' },
        { title: `I've got a "word" for you, homey: Dust` },
        { title: 'Music never gets old' },
        { artist: 'Tom Petty', title: 'Running down a dream' },
        { artist: 'Tom Petty', title: 'Running down a dream (Intro)' },
        { artist: 'Tom Petty', title: 'Running down a dream (Intro DJ 1)' },
        { artist: 'Tom Petty', title: 'Running down a dream (Intro DJ 2)' },
        { artist: 'Tom Petty', title: 'Running down a dream (Outro)' },
        { artist: 'Tom Petty', title: 'Running down a dream (Outro DJ 1)' },
        { artist: 'Tom Petty', title: 'Running down a dream (Outro DJ 2)' },
        { artist: 'Heart', title: 'Barracuda' },
        { artist: 'Heart', title: 'Barracuda (Intro)' },
        { artist: 'Heart', title: 'Barracuda (Intro DJ 1)' },
        { artist: 'Heart', title: 'Barracuda (Intro DJ 2)' },
        { artist: 'Heart', title: 'Barracuda (Outro)' },
        { artist: 'Heart', title: 'Barracuda (Outro DJ 1)' },
        { artist: 'Heart', title: 'Barracuda (Outro DJ 2)' },
        { artist: 'Joe Cocker', title: 'Woman to woman' },
        { artist: 'Joe Cocker', title: 'Woman to woman (Intro)' },
        { artist: 'Joe Cocker', title: 'Woman to woman (Intro DJ 1)' },
        { artist: 'Joe Cocker', title: 'Woman to woman (Intro DJ 2)' },
        { artist: 'Joe Cocker', title: 'Woman to woman (Outro)' },
        { artist: 'Joe Cocker', title: 'Woman to woman (Outro DJ 1)' },
        { artist: 'Joe Cocker', title: 'Woman to woman (Outro DJ 2)' },
        { artist: 'Rod Stewart', title: 'Young Turks' },
        { artist: 'Rod Stewart', title: 'Young Turks (Intro)' },
        { artist: 'Rod Stewart', title: 'Young Turks (Intro DJ 1)' },
        { artist: 'Rod Stewart', title: 'Young Turks (Intro DJ 2)' },
        { artist: 'Rod Stewart', title: 'Young Turks (Outro)' },
        { artist: 'Rod Stewart', title: 'Young Turks (Outro DJ 1)' },
        { artist: 'Rod Stewart', title: 'Young Turks (Outro DJ 2)' },
        { artist: 'David Bowie', title: 'Somebody up there likes me' },
        { artist: 'David Bowie', title: 'Somebody up there likes me (Intro)' },
        { artist: 'David Bowie', title: 'Somebody up there likes me (Intro DJ 1)' },
        { artist: 'David Bowie', title: 'Somebody up there likes me (Intro DJ 2)' },
        { artist: 'David Bowie', title: 'Somebody up there likes me (Outro)' },
        { artist: 'David Bowie', title: 'Somebody up there likes me (Outro DJ 1)' },
        { artist: 'Grand funk railroad', title: 'Some kind of wonderful' },
        { artist: 'Grand funk railroad', title: 'Some kind of wonderful (Intro)' },
        { artist: 'Grand funk railroad', title: 'Some kind of wonderful (Intro DJ 1)' },
        { artist: 'Grand funk railroad', title: 'Some kind of wonderful (Intro DJ 2)' },
        { artist: 'Grand funk railroad', title: 'Some kind of wonderful (Outro)' },
        { artist: 'Grand funk railroad', title: 'Some kind of wonderful (Outro DJ 1)' },
        { artist: 'Grand funk railroad', title: 'Some kind of wonderful (Outro DJ 2)' },
        { artist: 'KISS', title: 'Strutter' },
        { artist: 'KISS', title: 'Strutter (Intro)' },
        { artist: 'KISS', title: 'Strutter (Intro DJ 1)' },
        { artist: 'KISS', title: 'Strutter (Intro DJ 2)' },
        { artist: 'KISS', title: 'Strutter (Outro)' },
        { artist: 'KISS', title: 'Strutter (Outro DJ 1)' },
        { artist: 'KISS', title: 'Strutter (Outro DJ 2)' },
        { artist: 'Toto', title: 'Hold the line' },
        { artist: 'Toto', title: 'Hold the line (Intro)' },
        { artist: 'Toto', title: 'Hold the line (Outro)' },
        { artist: 'Creedence clearwater revival', title: 'Green river' },
        { artist: 'Creedence clearwater revival', title: 'Green river (Intro)' },
        { artist: 'Creedence clearwater revival', title: 'Green river (Intro DJ 1)' },
        { artist: 'Creedence clearwater revival', title: 'Green river (Intro DJ 2)' },
        { artist: 'Creedence clearwater revival', title: 'Green river (Outro)' },
        { artist: 'Creedence clearwater revival', title: 'Green river (Outro DJ 1)' },
        { artist: 'The Who', title: 'Eminence front' },
        { artist: 'The Who', title: 'Eminence front (Intro)' },
        { artist: 'The Who', title: 'Eminence front (Intro DJ 1)' },
        { artist: 'The Who', title: 'Eminence front (Intro DJ 2)' },
        { artist: 'The Who', title: 'Eminence front (Outro)' },
        { artist: 'The Who', title: 'Eminence front (Outro DJ 1)' },
        { artist: 'The Who', title: 'Eminence front (Outro DJ 2)' },
        { artist: 'America', title: 'A horse with no name' },
        { artist: 'America', title: 'A horse with no name (Intro)' },
        { artist: 'America', title: 'A horse with no name (Intro DJ 1)' },
        { artist: 'America', title: 'A horse with no name (Intro DJ 2)' },
        { artist: 'America', title: 'A horse with no name (Outro)' },
        { artist: 'America', title: 'A horse with no name (Outro DJ 1)' },
        { artist: 'America', title: 'A horse with no name (Outro DJ 2)' },
        { artist: 'Foghat', title: 'Slow ride' },
        { artist: 'Foghat', title: 'Slow ride (Intro)' },
        { artist: 'Foghat', title: 'Slow ride (Intro DJ 1)' },
        { artist: 'Foghat', title: 'Slow ride (Intro DJ 2)' },
        { artist: 'Foghat', title: 'Slow ride (Outro)' },
        { artist: 'Foghat', title: 'Slow ride (Outro DJ 1)' },
        { artist: 'Foghat', title: 'Slow ride (Outro DJ 2)' },
        { artist: 'Billy Idol', title: 'White wedding' },
        { artist: 'Billy Idol', title: 'White wedding (Intro)' },
        { artist: 'Billy Idol', title: 'White wedding (Intro DJ 1)' },
        { artist: 'Billy Idol', title: 'White wedding (Intro DJ 2)' },
        { artist: 'Billy Idol', title: 'White wedding (Outro)' },
        { artist: 'Billy Idol', title: 'White wedding (Outro DJ 1)' },
        { artist: 'Billy Idol', title: 'White wedding (Outro DJ 2)' },
        { artist: 'Humble pie', title: 'Get down to it' },
        { artist: 'Humble pie', title: 'Get down to it (Intro)' },
        { artist: 'Humble pie', title: 'Get down to it (Intro DJ 1)' },
        { artist: 'Humble pie', title: 'Get down to it (Intro DJ 2)' },
        { artist: 'Humble pie', title: 'Get down to it (Outro)' },
        { artist: 'Humble pie', title: 'Get down to it (Outro DJ 1)' },
        { artist: 'Humble pie', title: 'Get down to it (Outro DJ 2)' },
        { artist: 'Eddie Money', title: 'Two tickets to paradise' },
        { artist: 'Eddie Money', title: 'Two tickets to paradise (Intro)' },
        { artist: 'Eddie Money', title: 'Two tickets to paradise (Intro DJ 1)' },
        { artist: 'Eddie Money', title: 'Two tickets to paradise (Intro DJ 2)' },
        { artist: 'Eddie Money', title: 'Two tickets to paradise (Outro)' },
        { artist: 'Eddie Money', title: 'Two tickets to paradise (Outro DJ 1)' },
        { artist: 'Eddie Money', title: 'Two tickets to paradise (Outro DJ 2)' },
        { artist: 'Boston', title: "Smokin'" },
        { artist: 'Boston', title: "Smokin' (Intro)" },
        { artist: 'Boston', title: "Smokin' (Intro DJ 1)" },
        { artist: 'Boston', title: "Smokin' (Intro DJ 2)" },
        { artist: 'Boston', title: "Smokin' (Outro)" },
        { artist: 'Boston', title: "Smokin' (Outro DJ 1)" },
        { artist: 'Boston', title: "Smokin' (Outro DJ 2)" },
        { artist: 'Lynyrd Skynyrd', title: 'Free bird' },
        { artist: 'Lynyrd Skynyrd', title: 'Free bird (Intro)' },
        { artist: 'Lynyrd Skynyrd', title: 'Free bird (Intro DJ 1)' },
        { artist: 'Lynyrd Skynyrd', title: 'Free bird (Intro DJ 2)' },
        { artist: 'Lynyrd Skynyrd', title: 'Free bird (Outro)' },
        { artist: 'Lynyrd Skynyrd', title: 'Free bird (Outro DJ 1)' },
        { artist: 'Lynyrd Skynyrd', title: 'Free bird (Outro DJ 2)' },
    ],
};
