import { Station } from '../stations';

export const CUTSCENE: Station = {
    title: 'Cutscene',
    hash: 'd4bcb8ae560e44080169e2b4a5ad03b8',
    alternatives: [
        { hash: '60830413ba2ce0a103e228e91adbe4e1' },
    ],
    tracks: [
        { title: 'Clip 1' }, { title: 'Clip 2' }, { title: 'Clip 3' },
        { title: 'Clip 4' }, { title: 'Clip 5' }, { title: 'Clip 6' },
        { title: 'Clip 7' }, { title: 'Clip 8' }, { title: 'Clip 9' },
        { title: 'Clip 10' }, { title: 'Clip 11' }, { title: 'Clip 12' },
        { title: 'Clip 13' }, { title: 'Clip 14' }, { title: 'Clip 15' },
        { title: 'Clip 16' }, { title: 'Clip 17' }, { title: 'Clip 18' },
        { title: 'Clip 19' }, { title: 'Clip 20' }, { title: 'Clip 21' },
        { title: 'Clip 22' }, { title: 'Clip 23' }, { title: 'Clip 24' },
        { title: 'Clip 25' }, { title: 'Clip 26' }, { title: 'Clip 27' },
        { title: 'Clip 28' }, { title: 'Clip 29' }, { title: 'Clip 30' },
        { title: 'Clip 31' }, { title: 'Clip 32' }, { title: 'Clip 33' },
        { title: 'Clip 34' }, { title: 'Clip 35' }, { title: 'Clip 36' },
        { title: 'Clip 37' }, { title: 'Clip 38' }, { title: 'Clip 39' },
        { title: 'Clip 40' }, { title: 'Clip 41' }, { title: 'Clip 42' },
        { title: 'Clip 43' }, { title: 'Clip 44' }, { title: 'Clip 45' },
        { title: 'Clip 46' }, { title: 'Clip 47' }, { title: 'Clip 48' },
        { title: 'Clip 49' }, { title: 'Clip 50' }, { title: 'Clip 51' },
        { title: 'Clip 52' }, { title: 'Clip 53' }, { title: 'Clip 54' },
        { title: 'Clip 55' }, { title: 'Clip 56' }, { title: 'Clip 57' },
        { title: 'Clip 58' }, { title: 'Clip 59' }, { title: 'Clip 60' },
        { title: 'Clip 61' }, { title: 'Clip 62' }, { title: 'Clip 63' },
        { title: 'Clip 64' }, { title: 'Clip 65' }, { title: 'Clip 66' },
        { title: 'Clip 67' }, { title: 'Clip 68' }, { title: 'Clip 69' },
        { title: 'Clip 70' }, { title: 'Clip 71' }, { title: 'Clip 72' },
        { title: 'Clip 73' }, { title: 'Clip 74' }, { title: 'Clip 75' },
        { title: 'Clip 76' }, { title: 'Clip 77' }, { title: 'Clip 78' },
        { title: 'Clip 79' }, { title: 'Clip 80' }, { title: 'Clip 81' },
        { title: 'Clip 82' }, { title: 'Clip 83' }, { title: 'Clip 84' },
        { title: 'Clip 85' }, { title: 'Clip 86' }, { title: 'Clip 87' },
        { title: 'Clip 88' }, { title: 'Clip 89' }, { title: 'Clip 90' },
        { title: 'Clip 91' }, { title: 'Clip 92' }, { title: 'Clip 93' },
        { title: 'Clip 94' }, { title: 'Clip 95' }, { title: 'Clip 96' },
        { title: 'Clip 97' }, { title: 'Clip 98' }, { title: 'Clip 99' },
        { title: 'Clip 100' }, { title: 'Clip 101' }, { title: 'Clip 102' },
        { title: 'Clip 103' }, { title: 'Clip 104' }, { title: 'Clip 105' },
        { title: 'Clip 106' }, { title: 'Clip 107' }, { title: 'Clip 108' },
        { title: 'Clip 109' }, { title: 'Clip 110' }, { title: 'Clip 111' },
        { title: 'Clip 112' }, { title: 'Clip 113' }, { title: 'Clip 114' },
        { title: 'Clip 115' }, { title: 'Clip 116' }, { title: 'Clip 117' },
        { title: 'Clip 118' }, { title: 'Clip 119' }, { title: 'Clip 120' },
        { title: 'Clip 121' }, { title: 'Clip 122' }, { title: 'Clip 123' },
        { title: 'Clip 124' }, { title: 'Clip 125' }, { title: 'Clip 126' },
        { title: 'Clip 127' }, { title: 'Clip 128' }, { title: 'Clip 129' },
        { title: 'Clip 130' }, { title: 'Clip 131' }, { title: 'Clip 132' },
        { title: 'Clip 133' }, { title: 'Clip 134' }, { title: 'Clip 135' },
        { title: 'Clip 136' }, { title: 'Clip 137' }, { title: 'Clip 138' },
        { title: 'Clip 139' }, { title: 'Clip 140' }, { title: 'Clip 141' },
    ],
};
