import { Station } from '../stations';

export const BOUNCE_FM: Station = {
    title: 'Bounce FM',
    hash: 'bbf21458f45989c1edaab9a61b13878b',
    alternatives: [
        { hash: '133045ed658c180481fd298e29a21a41' },
    ],
    tracks: [
        { title: 'Earthquake' },
        { title: 'Bridges open' },
        { title: 'Bone County open' },
        { title: 'Shake your ass' },
        { title: 'Primordial funk' },
        { title: 'Smelling like the funk' },
        { title: 'Stop funking around' },
        { title: 'Back up into something wet' },
        { title: 'Take it off baby' },
        { title: 'Blunted' },
        { title: 'A B C D Me' },
        { title: "Party 'til you poop" },
        { title: 'You lost the funk' },
        { title: 'No mental hospital can hold me' },
        { title: 'A shitty outlook on life' },
        { title: 'What have you been smoking?' },
        { title: 'Proper preperation prevents piss poor performance' },
        { title: 'Can you imagine me in handcuffs?' },
        { title: "I can't believe my lyin' eyes" },
        { title: "I'm not saying please" },
        { title: 'Doing it to you in your earhole' },
        { title: 'You know you want it' },
        { title: 'Stop towing the Funktapus mobile' },
        { title: "Would you believe they're paying me for this?" },
        { title: 'So you wanna be me?' },
        { title: 'Like a choo-choo' },
        { title: 'If I look back I see me coming' },
        { title: "There's a lot of stress out there" },
        { title: 'The Funktapus is like sushi' },
        { title: 'Those casinos are getting crazy' },
        { title: 'I know about the prune juice' },
        { title: 'Do fries go with that shake?' },
        { title: 'Funk is the DNA in rap' },
        { title: 'Everyone here is so fake' },
        { title: 'Sounds like you have a bipolar disorder' },
        { title: 'How do I get on the party ship?' },
        { title: 'Building in the desert' },
        { title: 'Lost a jumpjet' },
        { title: 'Evening 1' },
        { title: 'Evening 2' },
        { title: 'Morning 1' },
        { title: 'Morning 2' },
        { title: 'Morning 3' },
        { title: 'Night 1' },
        { title: 'Night 2' },
        { title: 'Fog 1' },
        { title: 'Fog 2' },
        { title: 'Smog' },
        { title: 'Rain 1' },
        { title: 'Rain 2' },
        { title: 'Sunny 1' },
        { title: 'Sunny 2' },
        { title: "Party ship's crash landed" },
        { title: "Until everyone's pregnant" },
        { title: 'The party never stops' },
        { title: 'Share your stash with everyone, baby' },
        { title: 'What did I do last night?' },
        { title: 'Ready to fly into space?' },
        { title: "Who's next on my wife?" },
        { title: "Nobody's sober at the party" },
        { artist: 'Ohio players', title: 'Love rollercoaster' },
        { artist: 'Ohio players', title: 'Love rollercoaster (Intro)' },
        { artist: 'Ohio players', title: 'Love rollercoaster (Intro DJ 1)' },
        { artist: 'Ohio players', title: 'Love rollercoaster (Intro DJ 2)' },
        { artist: 'Ohio players', title: 'Love rollercoaster (Outro)' },
        { artist: 'Ohio players', title: 'Love rollercoaster (Outro DJ 1)' },
        { artist: 'Ohio players', title: 'Love rollercoaster (Outro DJ 2)' },
        { artist: 'George Clinton', title: 'Loopzilla' },
        { artist: 'George Clinton', title: 'Loopzilla (Intro)' },
        { artist: 'George Clinton', title: 'Loopzilla (Intro DJ 1)' },
        { artist: 'George Clinton', title: 'Loopzilla (Intro DJ 2)' },
        { artist: 'George Clinton', title: 'Loopzilla (Outro)' },
        { artist: 'George Clinton', title: 'Loopzilla (Outro DJ 1)' },
        { artist: 'George Clinton', title: 'Loopzilla (Outro DJ 2)' },
        { artist: 'Cameo', title: 'Candy' },
        { artist: 'Cameo', title: 'Candy (Intro)' },
        { artist: 'Cameo', title: 'Candy (Intro DJ 1)' },
        { artist: 'Cameo', title: 'Candy (Intro DJ 2)' },
        { artist: 'Cameo', title: 'Candy (Outro)' },
        { artist: 'Cameo', title: 'Candy (Outro DJ 1)' },
        { artist: 'Cameo', title: 'Candy (Outro DJ 2)' },
        { artist: 'The gap band', title: 'You dropped a bomb on me' },
        { artist: 'The gap band', title: 'You dropped a bomb on me (Intro)' },
        { artist: 'The gap band', title: 'You dropped a bomb on me (Intro DJ 1)' },
        { artist: 'The gap band', title: 'You dropped a bomb on me (Intro DJ 2)' },
        { artist: 'The gap band', title: 'You dropped a bomb on me (Outro)' },
        { artist: 'The gap band', title: 'You dropped a bomb on me (Outro DJ 1)' },
        { artist: 'The gap band', title: 'You dropped a bomb on me (Outro DJ 2)' },
        { artist: 'Rick James', title: 'Cold blooded' },
        { artist: 'Rick James', title: 'Cold blooded (Intro)' },
        { artist: 'Rick James', title: 'Cold blooded (Intro DJ 1)' },
        { artist: 'Rick James', title: 'Cold blooded (Intro DJ 2)' },
        { artist: 'Rick James', title: 'Cold blooded (Outro)' },
        { artist: 'Rick James', title: 'Cold blooded (Outro DJ 1)' },
        { artist: 'Rick James', title: 'Cold blooded (Outro DJ 2)' },
        { artist: 'Zapp', title: 'I can make you dance' },
        { artist: 'Zapp', title: 'I can make you dance (Intro)' },
        { artist: 'Zapp', title: 'I can make you dance (Intro DJ 1)' },
        { artist: 'Zapp', title: 'I can make you dance (Intro DJ 2)' },
        { artist: 'Zapp', title: 'I can make you dance (Outro)' },
        { artist: 'Zapp', title: 'I can make you dance (Outro DJ 1)' },
        { artist: 'Zapp', title: 'I can make you dance (Outro DJ 2)' },
        { artist: 'Kool and the gang', title: 'Hollywood swinging' },
        { artist: 'Kool and the gang', title: 'Hollywood swinging (Intro)' },
        { artist: 'Kool and the gang', title: 'Hollywood swinging (Intro DJ 1)' },
        { artist: 'Kool and the gang', title: 'Hollywood swinging (Intro DJ 2)' },
        { artist: 'Kool and the gang', title: 'Hollywood swinging (Outro)' },
        { artist: 'Kool and the gang', title: 'Hollywood swinging (Outro DJ 1)' },
        { artist: 'Kool and the gang', title: 'Hollywood swinging (Outro DJ 2)' },
        { artist: 'Maze', title: 'Twilight' },
        { artist: 'Maze', title: 'Twilight (Intro)' },
        { artist: 'Maze', title: 'Twilight (Intro DJ 1)' },
        { artist: 'Maze', title: 'Twilight (Intro DJ 2)' },
        { artist: 'Maze', title: 'Twilight (Outro)' },
        { artist: 'Maze', title: 'Twilight (Outro DJ 1)' },
        { artist: 'Maze', title: 'Twilight (Outro DJ 2)' },
        { artist: 'Fat back', title: 'Yum yum' },
        { artist: 'Fat back', title: 'Yum yum (Intro)' },
        { artist: 'Fat back', title: 'Yum yum (Intro DJ 1)' },
        { artist: 'Fat back', title: 'Yum yum (Intro DJ 2)' },
        { artist: 'Fat back', title: 'Yum yum (Outro)' },
        { artist: 'Fat back', title: 'Yum yum (Outro DJ 1)' },
        { artist: 'Fat back', title: 'Yum yum (Outro DJ 2)' },
        { artist: 'Ronnie Hudson', title: 'West coast poplock' },
        { artist: 'Ronnie Hudson', title: 'West coast poplock (Intro)' },
        { artist: 'Ronnie Hudson', title: 'West coast poplock (Intro DJ 1)' },
        { artist: 'Ronnie Hudson', title: 'West coast poplock (Intro DJ 2)' },
        { artist: 'Ronnie Hudson', title: 'West coast poplock (Outro)' },
        { artist: 'Ronnie Hudson', title: 'West coast poplock (Outro DJ 1)' },
        { artist: 'Ronnie Hudson', title: 'West coast poplock (Outro DJ 2)' },
        { artist: 'Lakeside', title: 'Fantastic voyage' },
        { artist: 'Lakeside', title: 'Fantastic voyage (Intro)' },
        { artist: 'Lakeside', title: 'Fantastic voyage (Intro DJ 1)' },
        { artist: 'Lakeside', title: 'Fantastic voyage (Intro DJ 2)' },
        { artist: 'Lakeside', title: 'Fantastic voyage (Outro)' },
        { artist: 'Lakeside', title: 'Fantastic voyage (Outro DJ 1)' },
        { artist: 'Lakeside', title: 'Fantastic voyage (Outro DJ 2)' },
        { artist: 'Dazz Band', title: 'Let it whip' },
        { artist: 'Dazz Band', title: 'Let it whip (Intro)' },
        { artist: 'Dazz Band', title: 'Let it whip (Intro DJ 1)' },
        { artist: 'Dazz Band', title: 'Let it whip (Intro DJ 2)' },
        { artist: 'Dazz Band', title: 'Let it whip (Outro)' },
        { artist: 'Dazz Band', title: 'Let it whip (Outro DJ 1)' },
        { artist: 'Dazz Band', title: 'Let it whip (Outro DJ 2)' },
        { artist: 'The Isley brothers', title: 'Between the sheets' },
        { artist: 'The Isley brothers', title: 'Between the sheets (Intro)' },
        { artist: 'The Isley brothers', title: 'Between the sheets (Intro DJ 1)' },
        { artist: 'The Isley brothers', title: 'Between the sheets (Intro DJ 2)' },
        { artist: 'The Isley brothers', title: 'Between the sheets (Outro)' },
        { artist: 'The Isley brothers', title: 'Between the sheets (Outro DJ 1)' },
        { artist: 'The Isley brothers', title: 'Between the sheets (Outro DJ 2)' },
        { artist: 'MFSB', title: 'Love is the message' },
        { artist: 'MFSB', title: 'Love is the message (Intro)' },
        { artist: 'MFSB', title: 'Love is the message (Intro DJ 1)' },
        { artist: 'MFSB', title: 'Love is the message (Intro DJ 2)' },
        { artist: 'MFSB', title: 'Love is the message (Outro)' },
        { artist: 'MFSB', title: 'Love is the message (Outro DJ 1)' },
        { artist: 'MFSB', title: 'Love is the message (Outro DJ 2)' },
        { artist: 'Ohio players', title: 'Funky worm' },
        { artist: 'Ohio players', title: 'Funky worm (Intro)' },
        { artist: 'Ohio players', title: 'Funky worm (Intro DJ 1)' },
        { artist: 'Ohio players', title: 'Funky worm (Intro DJ 2)' },
        { artist: 'Ohio players', title: 'Funky worm (Outro)' },
        { artist: 'Ohio players', title: 'Funky worm (Outro DJ 1)' },
        { artist: 'Ohio players', title: 'Funky worm (Outro DJ 2)' },
        { artist: 'Roy Ayers', title: 'Running away' },
        { artist: 'Roy Ayers', title: 'Running away (Intro)' },
        { artist: 'Roy Ayers', title: 'Running away (Intro DJ 1)' },
        { artist: 'Roy Ayers', title: 'Running away (Intro DJ 2)' },
        { artist: 'Roy Ayers', title: 'Running away (Outro)' },
        { artist: 'Roy Ayers', title: 'Running away (Outro DJ 1)' },
        { artist: 'Roy Ayers', title: 'Running away (Outro DJ 2)' },
        { artist: 'Johnny Harris', title: 'Odyssey' },
        { artist: 'Johnny Harris', title: 'Odyssey (Intro)' },
        { artist: 'Johnny Harris', title: 'Odyssey (Intro DJ 1)' },
        { artist: 'Johnny Harris', title: 'Odyssey (Intro DJ 2)' },
        { artist: 'Johnny Harris', title: 'Odyssey (Outro)' },
        { artist: 'Johnny Harris', title: 'Odyssey (Outro DJ 1)' },
        { artist: 'Johnny Harris', title: 'Odyssey (Outro DJ 2)' },
    ],
};
