import { Station } from '../stations';

export const SFUR: Station = {
    title: 'SFUR',
    hash: '2c42bd257849aa8fddb23a70785b5e8c',
    tracks: [
        { title: 'Earthquake' },
        { title: 'Bridges open' },
        { title: 'Bone County open' },
        { title: "I'd like to request a song" },
        { title: 'Play some Wagner' },
        { title: 'Shut up and dance, you fools!' },
        { title: 'I am a rebel' },
        { title: 'I come to America' },
        { title: 'People cry when they see my record collection' },
        { title: 'The computers have taken over' },
        { title: 'European style... shaved' },
        { title: 'Keeping it on a housey tip now' },
        { title: 'Keep the party moving in here' },
        { title: 'Has that dealer turned up yet?' },
        { title: 'Would you like a pillow?' },
        { title: "Don't make me go to rehab" },
        { title: 'I want to cry' },
        { title: 'I am communing with you' },
        { title: 'We are like dolphins clicking' },
        { title: 'Harder, faster, deeper' },
        { title: "Let's party" },
        { title: 'Living in a digital future' },
        { title: 'I love complete strangers' },
        { title: 'I love you, San Fierro' },
        { title: 'I went to Liberty City once' },
        { title: 'Cigarette papers' },
        { title: 'Evening 1' },
        { title: 'Evening 2' },
        { title: 'Evening 3' },
        { title: 'Morning 1' },
        { title: 'Morning 2' },
        { title: 'Morning 3' },
        { title: 'Night 1' },
        { title: 'Night 2' },
        { title: 'Night 3' },
        { artist: 'Joe Smooth', title: 'Promised land' },
        { artist: 'Joe Smooth', title: 'Promised land (Intro DJ 1)' },
        { artist: 'Joe Smooth', title: 'Promised land (Intro DJ 2)' },
        { artist: 'Joe Smooth', title: 'Promised land (Outro DJ 1)' },
        { artist: 'Joe Smooth', title: 'Promised land (Outro DJ 2)' },
        { artist: '808 state', title: 'Pacific' },
        { artist: '808 state', title: 'Pacific (Intro DJ 1)' },
        { artist: '808 state', title: 'Pacific (Intro DJ 2)' },
        { artist: '808 state', title: 'Pacific (Outro DJ 1)' },
        { artist: '808 state', title: 'Pacific (Outro DJ 2)' },
        { artist: 'A guy called Gerald', title: 'Voodoo Ray' },
        { artist: 'A guy called Gerald', title: 'Voodoo Ray (Intro DJ 1)' },
        { artist: 'A guy called Gerald', title: 'Voodoo Ray (Intro DJ 2)' },
        { artist: 'A guy called Gerald', title: 'Voodoo Ray (Outro DJ 1)' },
        { artist: 'A guy called Gerald', title: 'Voodoo Ray (Outro DJ 2)' },
        { artist: 'Frankie Knuckles', title: 'Your love' },
        { artist: 'Frankie Knuckles', title: 'Your love (Intro DJ 1)' },
        { artist: 'Frankie Knuckles', title: 'Your love (Intro DJ 2)' },
        { artist: 'Frankie Knuckles', title: 'Your love (Outro DJ 1)' },
        { artist: 'Frankie Knuckles', title: 'Your love (Outro DJ 2)' },
        { artist: 'Raze', title: 'Break 4 love' },
        { artist: 'Raze', title: 'Break 4 love (Intro DJ 1)' },
        { artist: 'Raze', title: 'Break 4 love (Intro DJ 2)' },
        { artist: 'Raze', title: 'Break 4 love (Outro DJ 1)' },
        { artist: 'Raze', title: 'Break 4 love (Outro DJ 2)' },
        { artist: 'Cultural vibe', title: 'Ma foom bey' },
        { artist: 'Cultural vibe', title: 'Ma foom bey (Intro DJ 1)' },
        { artist: 'Cultural vibe', title: 'Ma foom bey (Intro DJ 2)' },
        { artist: 'Cultural vibe', title: 'Ma foom bey (Outro DJ 1)' },
        { artist: 'Cultural vibe', title: 'Ma foom bey (Outro DJ 2)' },
        { artist: 'Jomanda', title: 'Make my body rock' },
        { artist: 'Jomanda', title: 'Make my body rock (Intro DJ 1)' },
        { artist: 'Jomanda', title: 'Make my body rock (Intro DJ 2)' },
        { artist: 'Jomanda', title: 'Make my body rock (Outro DJ 1)' },
        { artist: 'Jomanda', title: 'Make my body rock (Outro DJ 2)' },
        { artist: 'Ce Ce Rogers', title: 'Someday' },
        { artist: 'Ce Ce Rogers', title: 'Someday (Intro DJ 1)' },
        { artist: 'Ce Ce Rogers', title: 'Someday (Intro DJ 2)' },
        { artist: 'Ce Ce Rogers', title: 'Someday (Outro DJ 1)' },
        { artist: 'Ce Ce Rogers', title: 'Someday (Outro DJ 2)' },
        { artist: 'Nightwriters', title: 'Let the music use you' },
        { artist: 'Nightwriters', title: 'Let the music use you (Intro DJ 1)' },
        { artist: 'Nightwriters', title: 'Let the music use you (Intro DJ 2)' },
        { artist: 'Nightwriters', title: 'Let the music use you (Outro DJ 1)' },
        { artist: 'Nightwriters', title: 'Let the music use you (Outro DJ 2)' },
        { artist: 'Mr Fingers', title: 'Can you feel it?' },
        { artist: 'Mr Fingers', title: 'Can you feel it? (Intro DJ 1)' },
        { artist: 'Mr Fingers', title: 'Can you feel it? (Intro DJ 2)' },
        { artist: 'Mr Fingers', title: 'Can you feel it? (Outro DJ 1)' },
        { artist: 'Mr Fingers', title: 'Can you feel it? (Outro DJ 2)' },
        { artist: 'Marshall Jefferson', title: 'Move your body' },
        { artist: 'Marshall Jefferson', title: 'Move your body (Intro DJ 1)' },
        { artist: 'Marshall Jefferson', title: 'Move your body (Intro DJ 2)' },
        { artist: 'Marshall Jefferson', title: 'Move your body (Outro DJ 1)' },
        { artist: 'Marshall Jefferson', title: 'Move your body (Outro DJ 2)' },
        { artist: 'Maurice', title: 'This is acid' },
        { artist: 'Maurice', title: 'This is acid (Intro DJ 1)' },
        { artist: 'Maurice', title: 'This is acid (Intro DJ 2)' },
        { artist: 'Maurice', title: 'This is acid (Outro DJ 1)' },
        { artist: 'Maurice', title: 'This is acid (Outro DJ 2)' },
        { artist: 'The Todd Terry project', title: 'Weekend' },
        { artist: 'The Todd Terry project', title: 'Weekend (Intro DJ 1)' },
        { artist: 'The Todd Terry project', title: 'Weekend (Intro DJ 2)' },
        { artist: 'The Todd Terry project', title: 'Weekend (Outro DJ 1)' },
        { artist: 'The Todd Terry project', title: 'Weekend (Outro DJ 2)' },
        { artist: 'Fallout', title: 'The morning after' },
        { artist: 'Fallout', title: 'The morning after (Intro DJ 1)' },
        { artist: 'Fallout', title: 'The morning after (Intro DJ 2)' },
        { artist: 'Fallout', title: 'The morning after (Outro DJ 1)' },
        { artist: 'Fallout', title: 'The morning after (Outro DJ 2)' },
        { artist: 'Robert Owens', title: "I'll be your friend" },
        { artist: 'Robert Owens', title: "I'll be your friend (Intro DJ 1)" },
        { artist: 'Robert Owens', title: "I'll be your friend (Intro DJ 2)" },
        { artist: 'Robert Owens', title: "I'll be your friend (Outro DJ 1)" },
        { artist: 'Robert Owens', title: "I'll be your friend (Outro DJ 2)" },
        { artist: '28th street crew', title: 'I need a rythm' },
        { artist: '28th street crew', title: 'I need a rythm (Intro DJ 1)' },
        { artist: '28th street crew', title: 'I need a rythm (Intro DJ 2)' },
        { artist: '28th street crew', title: 'I need a rythm (Outro DJ 1)' },
        { artist: '28th street crew', title: 'I need a rythm (Outro DJ 2)' },
    ],
};
