import { Station } from '../stations';

export const RADIO_LOS_SANTOS: Station = {
    title: 'Radio Los Santos',
    hash: 'fcc7b4550abb177ea52aee563e562be5',
    alternatives: [
        { hash: '1e3a881621d466e9972213c6ed9b21d4' },
    ],
    tracks: [
        { title: 'Earthquake' },
        { title: 'Bridges open' },
        { title: 'Bone County open' },
        { title: 'Rappers and gangsters' },
        { title: 'The home of gangsta rap' },
        { title: 'Your man Julio G' },
        { title: 'The hottest shit around' },
        { title: 'Not the home of gangster fools' },
        { title: 'Original home of the drive-by' },
        { title: 'Smog 1' },
        { title: "Don't touch that dial" },
        { title: 'Smog 2' },
        { title: 'Burglary and carjacking are up' },
        { title: 'Self-styled audio boys from Scotland' },
        { title: 'My man Les in the north' },
        { title: 'I get it first, the others get it last' },
        { title: 'Sam and the boys from Liberty City' },
        { title: 'We play the real shit' },
        { title: 'The rest of the world can follow' },
        { title: 'Ruling the airwaves' },
        { title: 'Denise is desperate' },
        { title: 'Gang News' },
        { title: 'Grove Street' },
        { title: 'Major gang activity' },
        { title: 'Riot' },
        { title: 'Evening 1' },
        { title: 'Evening 2' },
        { title: 'Morning 1' },
        { title: 'Morning 2' },
        { title: 'Night 1' },
        { title: 'Night 2' },
        { title: 'Fog 1' },
        { title: 'Fog 2' },
        { title: 'Rain 1' },
        { title: 'Rain 2' },
        { title: 'Storm 1' },
        { title: 'Storm 2' },
        { title: 'Sunny 1' },
        { title: 'Sunny 2' },
        { title: 'Ident 1' },
        { title: 'Ident 2' },
        { title: 'Ident 3' },
        { title: 'Ident 4' },
        { title: 'Ident 5' },
        { title: 'Ident 6' },
        { title: 'Ident 7' },
        { title: 'Ident 8' },
        { title: 'Ident 9' },
        { title: 'Ident 10' },
        { title: 'Ident 11' },
        { artist: 'Dr Dre', title: 'Fuck with Dre day' },
        { artist: 'Dr Dre', title: 'Fuck with Dre day (Intro)' },
        { artist: 'Dr Dre', title: 'Fuck with Dre day (Intro DJ 1)' },
        { artist: 'Dr Dre', title: 'Fuck with Dre day (Intro DJ 2)' },
        { artist: 'Dr Dre', title: 'Fuck with Dre day (Outro)' },
        { artist: 'Dr Dre', title: 'Fuck with Dre day (Outro DJ 1)' },
        { artist: 'Dr Dre', title: 'Fuck with Dre day (Outro DJ 2)' },
        { artist: '2 Pac', title: "I don't give a fuck" },
        { artist: '2 Pac', title: "I don't give a fuck (Intro)" },
        { artist: '2 Pac', title: "I don't give a fuck (Intro DJ 1)" },
        { artist: '2 Pac', title: "I don't give a fuck (Intro DJ 2)" },
        { artist: '2 Pac', title: "I don't give a fuck (Outro)" },
        { artist: '2 Pac', title: "I don't give a fuck (Outro DJ 1)" },
        { artist: '2 Pac', title: "I don't give a fuck (Outro DJ 2)" },
        { artist: 'Dr Dre', title: "Nuthin' but a 'G' thang" },
        { artist: 'Dr Dre', title: "Nuthin' but a 'G' thang (Intro)" },
        { artist: 'Dr Dre', title: "Nuthin' but a 'G' thang (Intro DJ 1)" },
        { artist: 'Dr Dre', title: "Nuthin' but a 'G' thang (Intro DJ 2)" },
        { artist: 'Dr Dre', title: "Nuthin' but a 'G' thang (Outro)" },
        { artist: 'Dr Dre', title: "Nuthin' but a 'G' thang (Outro DJ 1)" },
        { artist: 'Dr Dre', title: "Nuthin' but a 'G' thang (Outro DJ 2)" },
        { artist: "Compton's most wanted", title: 'Hood took me under' },
        { artist: "Compton's most wanted", title: 'Hood took me under (Intro)' },
        { artist: "Compton's most wanted", title: 'Hood took me under (Intro DJ 1)' },
        { artist: "Compton's most wanted", title: 'Hood took me under (Intro DJ 2)' },
        { artist: "Compton's most wanted", title: 'Hood took me under (Outro)' },
        { artist: "Compton's most wanted", title: 'Hood took me under (Outro DJ 1)' },
        { artist: "Compton's most wanted", title: 'Hood took me under (Outro DJ 2)' },
        { artist: 'The doc', title: "It's funky enough" },
        { artist: 'The doc', title: "It's funky enough (Intro)" },
        { artist: 'The doc', title: "It's funky enough (Intro DJ 1)" },
        { artist: 'The doc', title: "It's funky enough (Intro DJ 2)" },
        { artist: 'The doc', title: "It's funky enough (Outro)" },
        { artist: 'The doc', title: "It's funky enough (Outro DJ 1)" },
        { artist: 'The doc', title: "It's funky enough (Outro DJ 2)" },
        { artist: 'NWA', title: 'Alwayz into something' },
        { artist: 'NWA', title: 'Alwayz into something (Intro)' },
        { artist: 'NWA', title: 'Alwayz into something (Intro DJ 1)' },
        { artist: 'NWA', title: 'Alwayz into something (Intro DJ 2)' },
        { artist: 'NWA', title: 'Alwayz into something (Outro)' },
        { artist: 'NWA', title: 'Alwayz into something (Outro DJ 1)' },
        { artist: 'NWA', title: 'Express yourself' },
        { artist: 'NWA', title: 'Express yourself (Intro)' },
        { artist: 'NWA', title: 'Express yourself (Intro DJ 1)' },
        { artist: 'NWA', title: 'Express yourself (Intro DJ 2)' },
        { artist: 'NWA', title: 'Express yourself (Outro)' },
        { artist: 'NWA', title: 'Express yourself (Outro DJ 1)' },
        { artist: 'Kid Frost', title: 'La raza' },
        { artist: 'Kid Frost', title: 'La raza (Intro)' },
        { artist: 'Kid Frost', title: 'La raza (Intro DJ 1)' },
        { artist: 'Kid Frost', title: 'La raza (Intro DJ 2)' },
        { artist: 'Kid Frost', title: 'La raza (Outro)' },
        { artist: 'Kid Frost', title: 'La raza (Outro DJ 1)' },
        { artist: 'Cypress hill', title: 'How I could just kill a man' },
        { artist: 'Cypress hill', title: 'How I could just kill a man (Intro)' },
        { artist: 'Cypress hill', title: 'How I could just kill a man (Intro DJ 1)' },
        { artist: 'Cypress hill', title: 'How I could just kill a man (Outro)' },
        { artist: 'Cypress hill', title: 'How I could just kill a man (Outro DJ 1)' },
        { artist: 'Above the law', title: 'Murder rap' },
        { artist: 'Above the law', title: 'Murder rap (Intro)' },
        { artist: 'Above the law', title: 'Murder rap (Intro DJ 1)' },
        { artist: 'Above the law', title: 'Murder rap (Intro DJ 2)' },
        { artist: 'Above the law', title: 'Murder rap (Outro)' },
        { artist: 'Above the law', title: 'Murder rap (Outro DJ 1)' },
        { artist: 'Above the law', title: 'Murder rap (Outro DJ 2)' },
        { artist: 'Eazy E', title: 'Eazy-er said than done' },
        { artist: 'Eazy E', title: 'Eazy-er said than done (Intro)' },
        { artist: 'Eazy E', title: 'Eazy-er said than done (Intro DJ 1)' },
        { artist: 'Eazy E', title: 'Eazy-er said than done (Intro DJ 2)' },
        { artist: 'Eazy E', title: 'Eazy-er said than done (Outro)' },
        { artist: 'Eazy E', title: 'Eazy-er said than done (Outro DJ 1)' },
        { artist: 'Eazy E', title: 'Eazy-er said than done (Outro DJ 2)' },
        { artist: 'Da lench mob', title: 'Guerillas in tha mist' },
        { artist: 'Da lench mob', title: 'Guerillas in tha mist (Intro)' },
        { artist: 'Da lench mob', title: 'Guerillas in tha mist (Intro DJ 1)' },
        { artist: 'Da lench mob', title: 'Guerillas in tha mist (Intro DJ 2)' },
        { artist: 'Da lench mob', title: 'Guerillas in tha mist (Outro)' },
        { artist: 'Da lench mob', title: 'Guerillas in tha mist (Outro DJ 1)' },
        { artist: 'Da lench mob', title: 'Guerillas in tha mist (Outro DJ 2)' },
        { artist: 'Ice cube', title: 'It was a good day' },
        { artist: 'Ice cube', title: 'It was a good day (Intro)' },
        { artist: 'Ice cube', title: 'It was a good day (Intro DJ 1)' },
        { artist: 'Ice cube', title: 'It was a good day (Outro)' },
        { artist: 'Ice cube', title: 'It was a good day (Outro DJ 1)' },
        { artist: 'Ice cube', title: 'Check yo self' },
        { artist: 'Ice cube', title: 'Check yo self (Intro)' },
        { artist: 'Ice cube', title: 'Check yo self (Intro DJ 1)' },
        { artist: 'Ice cube', title: 'Check yo self (Intro DJ 2)' },
        { artist: 'Ice cube', title: 'Check yo self (Outro)' },
        { artist: 'Ice cube', title: 'Check yo self (Outro DJ 1)' },
        { artist: 'Ice cube', title: 'Check yo self (Outro DJ 2)' },
        { artist: 'Dr Dre', title: 'Deep cover' },
        { artist: 'Dr Dre', title: 'Deep cover (Intro)' },
        { artist: 'Dr Dre', title: 'Deep cover (Intro DJ 1)' },
        { artist: 'Dr Dre', title: 'Deep cover (Outro)' },
        { artist: 'Dr Dre', title: 'Deep cover (Outro DJ 1)' },
        { artist: 'Dr Dre', title: 'Deep cover (Outro DJ 2)' },
        { artist: 'Too short', title: 'The ghetto' },
        { artist: 'Too short', title: 'The ghetto (Intro)' },
        { artist: 'Too short', title: 'The ghetto (Outro)' },
        { artist: 'Too short', title: 'The ghetto (Outro DJ 1)' },
        { artist: 'Too short', title: 'The ghetto (Outro DJ 2)' },
    ],
};
