import { Station } from '../stations';

export const RADIO_X: Station = {
    title: 'Radio X',
    hash: '4fd83ffca7302ef1d952ba686c0cae32',
    alternatives: [
        { hash: '3483c1c0bf6c76696dc9208d84562757' },
    ],
    tracks: [
        { title: 'Earthquake' },
        { title: 'Bridges open' },
        { title: 'Bone County open' },
        { title: 'Constant bombardment' },
        { title: 'Being a DJ is so hard' },
        { title: 'I have to work so hard' },
        { title: 'People over thirty' },
        { title: 'Sage' },
        { title: 'Guys in skirts' },
        { title: 'No tracers yet' },
        { title: 'That bitch at the record store' },
        { title: 'One must always go forward' },
        { title: 'Yes, that is my real name' },
        { title: 'Like a big mix tape' },
        { title: 'God I love crying' },
        { title: 'Celtic tattoo' },
        { title: 'You look like you need rehab' },
        { title: 'Sage? What a stupid name' },
        { title: 'Rap crisis' },
        { title: 'New casino' },
        { title: 'Weed burned down' },
        { title: 'Riot' },
        { title: 'Evening 1' },
        { title: 'Evening 2' },
        { title: 'Morning 1' },
        { title: 'Morning 2' },
        { title: 'Night 1' },
        { title: 'Night 2' },
        { title: 'Fog 1' },
        { title: 'Fog 2' },
        { title: 'Rain 1' },
        { title: 'Rain 2' },
        { title: 'Storm' },
        { title: 'Sunny 1' },
        { title: 'Sunny 2' },
        { title: "We're the only identity you've got" },
        { title: 'This is our time' },
        { title: 'The id, the ego, ...' },
        { title: 'Self-important nihilists' },
        { title: 'At the end of the alphabet' },
        { title: "They don't care about money" },
        { title: 'Trust fund babies' },
        { title: 'The birthplace of modern rock' },
        { title: 'Jump off a bridge and die' },
        { title: 'Much better than real friends' },
        { title: 'Who cares about hunger' },
        { artist: 'Faith no more', title: 'Midlife crisis' },
        { artist: 'Faith no more', title: 'Midlife crisis (Intro)' },
        { artist: 'Faith no more', title: 'Midlife crisis (Intro DJ 1)' },
        { artist: 'Faith no more', title: 'Midlife crisis (Intro DJ 2)' },
        { artist: 'Faith no more', title: 'Midlife crisis (Outro)' },
        { artist: 'Faith no more', title: 'Midlife crisis (Outro DJ 1)' },
        { artist: 'Faith no more', title: 'Midlife crisis (Outro DJ 2)' },
        { artist: 'Primal scream', title: "Movin' on up" },
        { artist: 'Primal scream', title: "Movin' on up (Intro)" },
        { artist: 'Primal scream', title: "Movin' on up (Intro DJ 1)" },
        { artist: 'Primal scream', title: "Movin' on up (Intro DJ 2)" },
        { artist: 'Primal scream', title: "Movin' on up (Outro)" },
        { artist: 'Primal scream', title: "Movin' on up (Outro DJ 1)" },
        { artist: 'Primal scream', title: "Movin' on up (Outro DJ 2)" },
        { artist: 'Depeche mode', title: 'Personal Jesus' },
        { artist: 'Depeche mode', title: 'Personal Jesus (Intro)' },
        { artist: 'Depeche mode', title: 'Personal Jesus (Intro DJ 1)' },
        { artist: 'Depeche mode', title: 'Personal Jesus (Intro DJ 2)' },
        { artist: 'Depeche mode', title: 'Personal Jesus (Outro)' },
        { artist: 'Depeche mode', title: 'Personal Jesus (Outro DJ 1)' },
        { artist: 'Depeche mode', title: 'Personal Jesus (Outro DJ 2)' },
        { artist: 'Danzig', title: 'Mother' },
        { artist: 'Danzig', title: 'Mother (Intro)' },
        { artist: 'Danzig', title: 'Mother (Intro DJ 1)' },
        { artist: 'Danzig', title: 'Mother (Intro DJ 2)' },
        { artist: 'Danzig', title: 'Mother (Outro)' },
        { artist: 'Danzig', title: 'Mother (Outro DJ 1)' },
        { artist: 'Danzig', title: 'Mother (Outro DJ 2)' },
        { artist: 'Helmet', title: 'Unsung' },
        { artist: 'Helmet', title: 'Unsung (Intro)' },
        { artist: 'Helmet', title: 'Unsung (Intro DJ 1)' },
        { artist: 'Helmet', title: 'Unsung (Intro DJ 2)' },
        { artist: 'Helmet', title: 'Unsung (Outro)' },
        { artist: 'Helmet', title: 'Unsung (Outro DJ 1)' },
        { artist: 'Helmet', title: 'Unsung (Outro DJ 2)' },
        { artist: 'Living colour', title: 'Cult of personality' },
        { artist: 'Living colour', title: 'Cult of personality (Intro)' },
        { artist: 'Living colour', title: 'Cult of personality (Intro DJ 1)' },
        { artist: 'Living colour', title: 'Cult of personality (Intro DJ 2)' },
        { artist: 'Living colour', title: 'Cult of personality (Outro)' },
        { artist: 'Living colour', title: 'Cult of personality (Outro DJ 1)' },
        { artist: 'Living colour', title: 'Cult of personality (Outro DJ 2)' },
        { artist: 'Ozzy Osbourne', title: 'Hellraiser' },
        { artist: 'Ozzy Osbourne', title: 'Hellraiser (Intro)' },
        { artist: 'Ozzy Osbourne', title: 'Hellraiser (Intro DJ 1)' },
        { artist: 'Ozzy Osbourne', title: 'Hellraiser (Intro DJ 2)' },
        { artist: 'Ozzy Osbourne', title: 'Hellraiser (Outro)' },
        { artist: 'Ozzy Osbourne', title: 'Hellraiser (Outro DJ 1)' },
        { artist: 'Ozzy Osbourne', title: 'Hellraiser (Outro DJ 2)' },
        { artist: 'Rage against the machine', title: 'Killing in the name' },
        { artist: 'Rage against the machine', title: 'Killing in the name (Intro)' },
        { artist: 'Rage against the machine', title: 'Killing in the name (Intro DJ 1)' },
        { artist: 'Rage against the machine', title: 'Killing in the name (Intro DJ 2)' },
        { artist: 'Rage against the machine', title: 'Killing in the name (Outro)' },
        { artist: 'Rage against the machine', title: 'Killing in the name (Outro DJ 1)' },
        { artist: 'Rage against the machine', title: 'Killing in the name (Outro DJ 2)' },
        { artist: "Guns 'n' roses", title: 'Welcome to the jungle' },
        { artist: "Guns 'n' roses", title: 'Welcome to the jungle (Intro)' },
        { artist: "Guns 'n' roses", title: 'Welcome to the jungle (Intro DJ 1)' },
        { artist: "Guns 'n' roses", title: 'Welcome to the jungle (Intro DJ 2)' },
        { artist: "Guns 'n' roses", title: 'Welcome to the jungle (Outro)' },
        { artist: "Guns 'n' roses", title: 'Welcome to the jungle (Outro DJ 1)' },
        { artist: "Guns 'n' roses", title: 'Welcome to the jungle (Outro DJ 2)' },
        { artist: "Jane's addiction", title: 'Been caught stealing' },
        { artist: "Jane's addiction", title: 'Been caught stealing (Intro)' },
        { artist: "Jane's addiction", title: 'Been caught stealing (Intro DJ 1)' },
        { artist: "Jane's addiction", title: 'Been caught stealing (Intro DJ 2)' },
        { artist: "Jane's addiction", title: 'Been caught stealing (Outro)' },
        { artist: "Jane's addiction", title: 'Been caught stealing (Outro DJ 1)' },
        { artist: "Jane's addiction", title: 'Been caught stealing (Outro DJ 2)' },
        { artist: 'Soundgarden', title: 'Rusty cage' },
        { artist: 'Soundgarden', title: 'Rusty cage (Intro)' },
        { artist: 'Soundgarden', title: 'Rusty cage (Intro DJ 1)' },
        { artist: 'Soundgarden', title: 'Rusty cage (Intro DJ 2)' },
        { artist: 'Soundgarden', title: 'Rusty cage (Outro)' },
        { artist: 'Soundgarden', title: 'Rusty cage (Outro DJ 1)' },
        { artist: 'Soundgarden', title: 'Rusty cage (Outro DJ 2)' },
        { artist: 'L7', title: "Pretend that we're dead" },
        { artist: 'L7', title: "Pretend that we're dead (Intro)" },
        { artist: 'L7', title: "Pretend that we're dead (Intro DJ 1)" },
        { artist: 'L7', title: "Pretend that we're dead (Intro DJ 2)" },
        { artist: 'L7', title: "Pretend that we're dead (Outro)" },
        { artist: 'L7', title: "Pretend that we're dead (Outro DJ 1)" },
        { artist: 'L7', title: "Pretend that we're dead (Outro DJ 2)" },
        { artist: 'The stone roses', title: "Fool's gold" },
        { artist: 'The stone roses', title: "Fool's gold (Intro)" },
        { artist: 'The stone roses', title: "Fool's gold (Intro DJ 1)" },
        { artist: 'The stone roses', title: "Fool's gold (Intro DJ 2)" },
        { artist: 'The stone roses', title: "Fool's gold (Outro)" },
        { artist: 'The stone roses', title: "Fool's gold (Outro DJ 1)" },
        { artist: 'The stone roses', title: "Fool's gold (Outro DJ 2)" },
        { artist: 'Alice in chains', title: 'Them bones' },
        { artist: 'Alice in chains', title: 'Them bones (Intro)' },
        { artist: 'Alice in chains', title: 'Them bones (Intro DJ 1)' },
        { artist: 'Alice in chains', title: 'Them bones (Intro DJ 2)' },
        { artist: 'Alice in chains', title: 'Them bones (Outro)' },
        { artist: 'Alice in chains', title: 'Them bones (Outro DJ 1)' },
        { artist: 'Alice in chains', title: 'Them bones (Outro DJ 2)' },
        { artist: 'Stone temple pilots', title: 'Plush' },
        { artist: 'Stone temple pilots', title: 'Plush (Intro)' },
        { artist: 'Stone temple pilots', title: 'Plush (Outro)' },
    ],
};
