import { Station } from '../stations';

export const CSR: Station = {
    title: 'CSR',
    hash: '80b7cf701f555fc567e1254e7734cb0f',
    tracks: [
        { title: 'Earthquake' },
        { title: 'Bridges open' },
        { title: 'Bone County open' },
        { title: 'Never trust a big butt and a smile' },
        { title: 'Buying a cane' },
        { title: 'Momentum' },
        { title: 'Celebrate with cake commercial' },
        { title: 'Swing with your wife' },
        { title: 'People that can really sing' },
        { title: 'One is music, the other belongs in therapy' },
        { title: 'Sing my name' },
        { title: 'Get ready to get down' },
        { title: 'Contemporary soul radio' },
        { title: 'The home of modern soul' },
        { title: 'Get off your fat ass and dance' },
        { title: "I'm in love with a girl" },
        { title: 'Male chauvanist pigs' },
        { title: 'New casino' },
        { title: 'Weed burned down' },
        { title: 'UFOs' },
        { title: 'Evening' },
        { title: 'Morning 1' },
        { title: 'Morning 2' },
        { title: 'Night 1' },
        { title: 'Night 2' },
        { title: 'Fog 1' },
        { title: 'Fog 2' },
        { title: 'Rain 1' },
        { title: 'Rain 2' },
        { title: 'Sunny 1' },
        { title: 'Sunny 2' },
        { title: 'What do you call it...' },
        { title: 'What happens when you mix...' },
        { title: 'Old Jack?  We killed his old ass' },
        { title: 'Why are you dressed like a preppie?' },
        { title: 'CSR 103.9' },
        { title: 'Swing on this, baby' },
        { title: 'Sold my soul to the Devil' },
        { title: 'Soul has to have integrity' },
        { artist: 'Soul II soul', title: "Keep on movin'" },
        { artist: 'Soul II soul', title: "Keep on movin' (Intro)" },
        { artist: 'Soul II soul', title: "Keep on movin' (Intro DJ 1)" },
        { artist: 'Soul II soul', title: "Keep on movin' (Intro DJ 2)" },
        { artist: 'Soul II soul', title: "Keep on movin' (Outro)" },
        { artist: 'Soul II soul', title: "Keep on movin' (Outro DJ 1)" },
        { artist: 'Soul II soul', title: "Keep on movin' (Outro DJ 2)" },
        { artist: 'Samuelle', title: 'So you like what you see' },
        { artist: 'Samuelle', title: 'So you like what you see (Intro)' },
        { artist: 'Samuelle', title: 'So you like what you see (Intro DJ 1)' },
        { artist: 'Samuelle', title: 'So you like what you see (Intro DJ 2)' },
        { artist: 'Samuelle', title: 'So you like what you see (Outro)' },
        { artist: 'Samuelle', title: 'So you like what you see (Outro DJ 1)' },
        { artist: 'Samuelle', title: 'So you like what you see (Outro DJ 2)' },
        { artist: 'Ralph Tresvant', title: 'Sensitivity' },
        { artist: 'Ralph Tresvant', title: 'Sensitivity (Intro)' },
        { artist: 'Ralph Tresvant', title: 'Sensitivity (Intro DJ 1)' },
        { artist: 'Ralph Tresvant', title: 'Sensitivity (Intro DJ 2)' },
        { artist: 'Ralph Tresvant', title: 'Sensitivity (Outro)' },
        { artist: 'Ralph Tresvant', title: 'Sensitivity (Outro DJ 1)' },
        { artist: 'Ralph Tresvant', title: 'Sensitivity (Outro DJ 2)' },
        { artist: 'En vogue', title: "My lovin'" },
        { artist: 'En vogue', title: "My lovin' (Intro)" },
        { artist: 'En vogue', title: "My lovin' (Intro DJ 1)" },
        { artist: 'En vogue', title: "My lovin' (Intro DJ 2)" },
        { artist: 'En vogue', title: "My lovin' (Outro)" },
        { artist: 'En vogue', title: "My lovin' (Outro DJ 1)" },
        { artist: 'En vogue', title: "My lovin' (Outro DJ 2)" },
        { artist: 'SWV', title: "I'm so into you" },
        { artist: 'SWV', title: "I'm so into you (Intro)" },
        { artist: 'SWV', title: "I'm so into you (Intro DJ 1)" },
        { artist: 'SWV', title: "I'm so into you (Intro DJ 2)" },
        { artist: 'SWV', title: "I'm so into you (Outro)" },
        { artist: 'SWV', title: "I'm so into you (Outro DJ 1)" },
        { artist: 'SWV', title: "I'm so into you (Outro DJ 2)" },
        { artist: 'Guy', title: 'Groove me' },
        { artist: 'Guy', title: 'Groove me (Intro)' },
        { artist: 'Guy', title: 'Groove me (Intro DJ 1)' },
        { artist: 'Guy', title: 'Groove me (Intro DJ 2)' },
        { artist: 'Guy', title: 'Groove me (Outro)' },
        { artist: 'Guy', title: 'Groove me (Outro DJ 1)' },
        { artist: 'Guy', title: 'Groove me (Outro DJ 2)' },
        { artist: 'Johnny Gil', title: 'Rub you the right way' },
        { artist: 'Johnny Gil', title: 'Rub you the right way (Intro)' },
        { artist: 'Johnny Gil', title: 'Rub you the right way (Intro DJ 1)' },
        { artist: 'Johnny Gil', title: 'Rub you the right way (Intro DJ 2)' },
        { artist: 'Johnny Gil', title: 'Rub you the right way (Outro)' },
        { artist: 'Johnny Gil', title: 'Rub you the right way (Outro DJ 1)' },
        { artist: 'Johnny Gil', title: 'Rub you the right way (Outro DJ 2)' },
        { artist: 'Boyz II men', title: 'Motown Philly' },
        { artist: 'Boyz II men', title: 'Motown Philly (Intro)' },
        { artist: 'Boyz II men', title: 'Motown Philly (Intro DJ 1)' },
        { artist: 'Boyz II men', title: 'Motown Philly (Intro DJ 2)' },
        { artist: 'Boyz II men', title: 'Motown Philly (Outro)' },
        { artist: 'Boyz II men', title: 'Motown Philly (Outro DJ 1)' },
        { artist: 'Boyz II men', title: 'Motown Philly (Outro DJ 2)' },
        { artist: 'Bobby Brown', title: "Don't be cruel" },
        { artist: 'Bobby Brown', title: "Don't be cruel (Intro)" },
        { artist: 'Bobby Brown', title: "Don't be cruel (Intro DJ 1)" },
        { artist: 'Bobby Brown', title: "Don't be cruel (Intro DJ 2)" },
        { artist: 'Bobby Brown', title: "Don't be cruel (Outro)" },
        { artist: 'Bobby Brown', title: "Don't be cruel (Outro DJ 1)" },
        { artist: 'Bobby Brown', title: "Don't be cruel (Outro DJ 2)" },
        { artist: 'Aaron Hall', title: "Don't be afraid" },
        { artist: 'Aaron Hall', title: "Don't be afraid (Intro)" },
        { artist: 'Aaron Hall', title: "Don't be afraid (Intro DJ 1)" },
        { artist: 'Aaron Hall', title: "Don't be afraid (Intro DJ 2)" },
        { artist: 'Aaron Hall', title: "Don't be afraid (Outro)" },
        { artist: 'Aaron Hall', title: "Don't be afraid (Outro DJ 1)" },
        { artist: 'Aaron Hall', title: "Don't be afraid (Outro DJ 2)" },
        { artist: 'Bell Biv Devoe', title: 'Poison' },
        { artist: 'Bell Biv Devoe', title: 'Poison (Intro)' },
        { artist: 'Bell Biv Devoe', title: 'Poison (Intro DJ 1)' },
        { artist: 'Bell Biv Devoe', title: 'Poison (Intro DJ 2)' },
        { artist: 'Bell Biv Devoe', title: 'Poison (Outro)' },
        { artist: 'Bell Biv Devoe', title: 'Poison (Outro DJ 1)' },
        { artist: 'Bell Biv Devoe', title: 'Poison (Outro DJ 2)' },
        { artist: "Wrecks 'n' effect", title: 'New Jack swing' },
        { artist: "Wrecks 'n' effect", title: 'New Jack swing (Intro)' },
        { artist: "Wrecks 'n' effect", title: 'New Jack swing (Intro DJ 1)' },
        { artist: "Wrecks 'n' effect", title: 'New Jack swing (Intro DJ 2)' },
        { artist: "Wrecks 'n' effect", title: 'New Jack swing (Outro)' },
        { artist: "Wrecks 'n' effect", title: 'New Jack swing (Outro DJ 1)' },
        { artist: "Wrecks 'n' effect", title: 'New Jack swing (Outro DJ 2)' },
        { artist: 'Today', title: 'I got the feeling' },
        { artist: 'Today', title: 'I got the feeling (Intro)' },
        { artist: 'Today', title: 'I got the feeling (Intro DJ 1)' },
        { artist: 'Today', title: 'I got the feeling (Intro DJ 2)' },
        { artist: 'Today', title: 'I got the feeling (Outro)' },
        { artist: 'Today', title: 'I got the feeling (Outro DJ 1)' },
        { artist: 'Today', title: 'I got the feeling (Outro DJ 2)' },
    ],
};
