import { Station } from '../stations';

export const K_JAH: Station = {
    title: 'K-JAH',
    hash: '65e0bea63444d87f74f6ef25388310b7',
    alternatives: [
        { hash: '468c77c46777bf877de765aad8043b0c' },
    ],
    tracks: [
        { title: 'Earthquake' },
        { title: 'Bridges open' },
        { title: 'Bone County open' },
        { title: 'Actor Johnny' },
        { title: 'Beware of the parlour tricks' },
        { title: 'Yeah, this is K-JAH West' },
        { title: 'Where is the love gone?' },
        { title: 'My best friend got stolen away' },
        { title: "I'll get myself in line" },
        { title: 'Caught the acting bug' },
        { title: "He's no rockstar" },
        { title: 'That sound like a good idea' },
        { title: 'They just lock you up' },
        { title: 'Snow in Jamaica' },
        { title: 'I love my music' },
        { title: 'All they do is smoke' },
        { title: 'A straight man' },
        { title: 'The British' },
        { title: 'So you want to be a rude boy?' },
        { title: 'Smoking break' },
        { title: "If you're working, quit" },
        { title: "More smokin' reggae" },
        { title: 'Dreddlocks gonna save us all' },
        { title: 'Mash it up' },
        { title: 'To all you scientists' },
        { title: "You don't need that shit" },
        { title: 'UFOs' },
        { title: "If people don't chill" },
        { title: 'Foolishness of Babylon' },
        { title: 'Evening 1' },
        { title: 'Evening 2' },
        { title: 'Morning 1' },
        { title: 'Morning 2' },
        { title: 'Night 1' },
        { title: 'Night 2' },
        { title: 'Fog 1' },
        { title: 'Fog 2' },
        { title: 'Rain 1' },
        { title: 'Rain 2' },
        { title: 'Storm' },
        { title: 'Sunny 1' },
        { title: 'Sunny 2' },
        { title: "That ain't bass" },
        { title: 'A breath of fresh air' },
        { title: 'Stop working' },
        { title: 'K-JAH west' },
        { title: 'Put your guns down' },
        { title: 'We are pilgrims' },
        { title: "Winners don't use hard drugs" },
        { title: 'Cool out with K-JAH' },
        { title: 'No argument now' },
        { title: 'The best in reggae' },
        { artist: 'Augustus Pablo', title: 'King Tubby meets the rockers uptown' },
        { artist: 'Augustus Pablo', title: 'King Tubby meets the rockers uptown (Intro)' },
        { artist: 'Augustus Pablo', title: 'King Tubby meets the rockers uptown (Intro DJ 1)' },
        { artist: 'Augustus Pablo', title: 'King Tubby meets the rockers uptown (Intro DJ 2)' },
        { artist: 'Augustus Pablo', title: 'King Tubby meets the rockers uptown (Outro)' },
        { artist: 'Augustus Pablo', title: 'King Tubby meets the rockers uptown (Outro DJ 1)' },
        { artist: 'Augustus Pablo', title: 'King Tubby meets the rockers uptown (Outro DJ 2)' },
        { artist: 'Toots and The maytals', title: 'Funky Kingston' },
        { artist: 'Toots and The maytals', title: 'Funky Kingston (Intro)' },
        { artist: 'Toots and The maytals', title: 'Funky Kingston (Intro DJ 1)' },
        { artist: 'Toots and The maytals', title: 'Funky Kingston (Intro DJ 2)' },
        { artist: 'Toots and The maytals', title: 'Funky Kingston (Outro)' },
        { artist: 'Toots and The maytals', title: 'Funky Kingston (Outro DJ 1)' },
        { artist: 'Toots and The maytals', title: 'Funky Kingston (Outro DJ 2)' },
        { artist: 'Blood sisters', title: 'Ring my bell' },
        { artist: 'Blood sisters', title: 'Ring my bell (Intro)' },
        { artist: 'Blood sisters', title: 'Ring my bell (Intro DJ 1)' },
        { artist: 'Blood sisters', title: 'Ring my bell (Intro DJ 2)' },
        { artist: 'Blood sisters', title: 'Ring my bell (Outro)' },
        { artist: 'Blood sisters', title: 'Ring my bell (Outro DJ 1)' },
        { artist: 'Blood sisters', title: 'Ring my bell (Outro DJ 2)' },
        { artist: 'Black harmony', title: "Don't let it go to your head" },
        { artist: 'Black harmony', title: "Don't let it go to your head (Intro)" },
        { artist: 'Black harmony', title: "Don't let it go to your head (Intro DJ 1)" },
        { artist: 'Black harmony', title: "Don't let it go to your head (Intro DJ 2)" },
        { artist: 'Black harmony', title: "Don't let it go to your head (Outro)" },
        { artist: 'Black harmony', title: "Don't let it go to your head (Outro DJ 1)" },
        { artist: 'Black harmony', title: "Don't let it go to your head (Outro DJ 2)" },
        { artist: 'Dennis Brown', title: 'Revolution' },
        { artist: 'Dennis Brown', title: 'Revolution (Intro)' },
        { artist: 'Dennis Brown', title: 'Revolution (Intro DJ 1)' },
        { artist: 'Dennis Brown', title: 'Revolution (Intro DJ 2)' },
        { artist: 'Dennis Brown', title: 'Revolution (Outro)' },
        { artist: 'Dennis Brown', title: 'Revolution (Outro DJ 1)' },
        { artist: 'Dennis Brown', title: 'Revolution (Outro DJ 2)' },
        { artist: 'I Roy', title: 'Sidewalk killer' },
        { artist: 'I Roy', title: 'Sidewalk killer (Intro)' },
        { artist: 'I Roy', title: 'Sidewalk killer (Intro DJ 1)' },
        { artist: 'I Roy', title: 'Sidewalk killer (Intro DJ 2)' },
        { artist: 'I Roy', title: 'Sidewalk killer (Outro)' },
        { artist: 'I Roy', title: 'Sidewalk killer (Outro DJ 1)' },
        { artist: 'I Roy', title: 'Sidewalk killer (Outro DJ 2)' },
        { artist: 'Shabba Ranks', title: 'Wicked inna bed' },
        { artist: 'Shabba Ranks', title: 'Wicked inna bed (Intro)' },
        { artist: 'Shabba Ranks', title: 'Wicked inna bed (Intro DJ 1)' },
        { artist: 'Shabba Ranks', title: 'Wicked inna bed (Intro DJ 2)' },
        { artist: 'Shabba Ranks', title: 'Wicked inna bed (Outro)' },
        { artist: 'Shabba Ranks', title: 'Wicked inna bed (Outro DJ 1)' },
        { artist: 'Shabba Ranks', title: 'Wicked inna bed (Outro DJ 2)' },
        { artist: 'Buju Banton', title: 'Batty rider' },
        { artist: 'Buju Banton', title: 'Batty rider (Intro)' },
        { artist: 'Buju Banton', title: 'Batty rider (Intro DJ 1)' },
        { artist: 'Buju Banton', title: 'Batty rider (Intro DJ 2)' },
        { artist: 'Buju Banton', title: 'Batty rider (Outro)' },
        { artist: 'Buju Banton', title: 'Batty rider (Outro DJ 1)' },
        { artist: 'Buju Banton', title: 'Batty rider (Outro DJ 2)' },
        { artist: 'Dillinger', title: 'Cocaine in my brain' },
        { artist: 'Dillinger', title: 'Cocaine in my brain (Intro)' },
        { artist: 'Dillinger', title: 'Cocaine in my brain (Intro DJ 1)' },
        { artist: 'Dillinger', title: 'Cocaine in my brain (Intro DJ 2)' },
        { artist: 'Dillinger', title: 'Cocaine in my brain (Outro)' },
        { artist: 'Dillinger', title: 'Cocaine in my brain (Outro DJ 1)' },
        { artist: 'Dillinger', title: 'Cocaine in my brain (Outro DJ 2)' },
        { artist: 'Willie Williams', title: 'Armagideon time' },
        { artist: 'Willie Williams', title: 'Armagideon time (Intro)' },
        { artist: 'Willie Williams', title: 'Armagideon time (Intro DJ 1)' },
        { artist: 'Willie Williams', title: 'Armagideon time (Intro DJ 2)' },
        { artist: 'Willie Williams', title: 'Armagideon time (Outro)' },
        { artist: 'Willie Williams', title: 'Armagideon time (Outro DJ 1)' },
        { artist: 'Willie Williams', title: 'Armagideon time (Outro DJ 2)' },
        { artist: 'Barrington Levy', title: 'Here I come' },
        { artist: 'Barrington Levy', title: 'Here I come (Intro)' },
        { artist: 'Barrington Levy', title: 'Here I come (Intro DJ 1)' },
        { artist: 'Barrington Levy', title: 'Here I come (Intro DJ 2)' },
        { artist: 'Barrington Levy', title: 'Here I come (Outro)' },
        { artist: 'Barrington Levy', title: 'Here I come (Outro DJ 1)' },
        { artist: 'Barrington Levy', title: 'Here I come (Outro DJ 2)' },
        { artist: 'Black Uhuru', title: 'Great train robbery' },
        { artist: 'Black Uhuru', title: 'Great train robbery (Intro)' },
        { artist: 'Black Uhuru', title: 'Great train robbery (Intro DJ 1)' },
        { artist: 'Black Uhuru', title: 'Great train robbery (Outro)' },
        { artist: 'Black Uhuru', title: 'Great train robbery (Outro DJ 1)' },
        { artist: 'Black Uhuru', title: 'Great train robbery (Outro DJ 2)' },
        { artist: 'Reggie Stepper', title: 'Drum pan sound' },
        { artist: 'Reggie Stepper', title: 'Drum pan sound (Intro)' },
        { artist: 'Reggie Stepper', title: 'Drum pan sound (Intro DJ 1)' },
        { artist: 'Reggie Stepper', title: 'Drum pan sound (Intro DJ 2)' },
        { artist: 'Reggie Stepper', title: 'Drum pan sound (Outro)' },
        { artist: 'Reggie Stepper', title: 'Drum pan sound (Outro DJ 1)' },
        { artist: 'Reggie Stepper', title: 'Drum pan sound (Outro DJ 2)' },
        { artist: 'The maytals', title: 'Pressure drop' },
        { artist: 'The maytals', title: 'Pressure drop (Intro)' },
        { artist: 'The maytals', title: 'Pressure drop (Intro DJ 1)' },
        { artist: 'The maytals', title: 'Pressure drop (Intro DJ 2)' },
        { artist: 'The maytals', title: 'Pressure drop (Outro)' },
        { artist: 'The maytals', title: 'Pressure drop (Outro DJ 1)' },
        { artist: 'The maytals', title: 'Pressure drop (Outro DJ 2)' },
        { artist: 'Max Romeo', title: 'Chase the Devil' },
        { artist: 'Max Romeo', title: 'Chase the Devil (Intro)' },
        { artist: 'Max Romeo', title: 'Chase the Devil (Intro DJ 1)' },
        { artist: 'Max Romeo', title: 'Chase the Devil (Intro DJ 2)' },
        { artist: 'Max Romeo', title: 'Chase the Devil (Outro)' },
        { artist: 'Max Romeo', title: 'Chase the Devil (Outro DJ 1)' },
        { artist: 'The pliars', title: 'Bam bam' },
        { artist: 'The pliars', title: 'Bam bam (Intro)' },
        { artist: 'The pliars', title: 'Bam bam (Intro DJ 1)' },
        { artist: 'The pliars', title: 'Bam bam (Intro DJ 2)' },
        { artist: 'The pliars', title: 'Bam bam (Outro)' },
        { artist: 'The pliars', title: 'Bam bam (Outro DJ 1)' },
    ],
};
