import { Station } from '../stations';

export const MASTER_SOUNDS: Station = {
    title: 'Master Sounds',
    hash: '743b480e6182f0a7795cddb2172cf45f',
    alternatives: [
        { hash: 'c6bad41f7c1da17516d7a3819c1bcbb4' },
    ],
    tracks: [
        { title: 'Earthquake' },
        { title: 'Bridges open' },
        { title: 'Bone County open' },
        { title: 'The art of love and sensible advice' },
        { title: 'Small packages' },
        { title: 'Heaven and back nineteen times' },
        { title: 'The love doctor' },
        { title: 'The master of the rare groove' },
        { title: 'We love you' },
        { title: 'I get a great boner' },
        { title: 'Eye-level with your kitty-cat' },
        { title: 'Big daddy' },
        { title: "Keep the groove groovin'" },
        { title: "Lovin' you, coz you're my bitch" },
        { title: "It's all pink on the inside" },
        { title: "You're tuned into who?" },
        { title: 'A little dude with an attitude' },
        { title: "I'm about to suck you right on up" },
        { title: 'Playing it for keeps' },
        { title: 'Right in your earhole, 3D style' },
        { title: 'Gonna end up in the hospital' },
        { title: 'Too much soul' },
        { title: 'Let me check out your headlights' },
        { title: 'My book' },
        { title: 'A.k.a. Love Giant' },
        { title: "I know you thinkin' girl" },
        { title: "Don't be a fool and be defiant" },
        { title: 'How tall are you?' },
        { title: 'Your attitude is disgusting' },
        { title: 'What was that racket last night?' },
        { title: 'UFOs' },
        { title: 'Burglaries' },
        { title: 'Mafia family' },
        { title: 'Policemen on trial' },
        { title: 'Racing in the countryside' },
        { title: 'Evening 1' },
        { title: 'Evening 2' },
        { title: 'Morning 1' },
        { title: 'Morning 2' },
        { title: 'Night 1' },
        { title: 'Night 2' },
        { title: 'Fog 1' },
        { title: 'Fog 2' },
        { title: 'Fog 3' },
        { title: 'Rain 1' },
        { title: 'Rain 2' },
        { title: 'Sunny' },
        { title: 'The home of cool rare grooves' },
        { title: "It's the Love Giant" },
        { title: 'Before it got sampled' },
        { title: "We're bringing it back" },
        { title: 'When the rhythm method was king' },
        { title: "Big daddy's back in town" },
        { title: 'Find a beat to steer you' },
        { title: 'Stop, listen, and learn' },
        { artist: 'Charles Wright', title: 'Express yourself' },
        { artist: 'Charles Wright', title: 'Express yourself (Intro)' },
        { artist: 'Charles Wright', title: 'Express yourself (Intro DJ 1)' },
        { artist: 'Charles Wright', title: 'Express yourself (Intro DJ 2)' },
        { artist: 'Charles Wright', title: 'Express yourself (Outro)' },
        { artist: 'Charles Wright', title: 'Express yourself (Outro DJ 1)' },
        { artist: 'Charles Wright', title: 'Express yourself (Outro DJ 2)' },
        { artist: 'Booker T and the MGs', title: 'Green onions' },
        { artist: 'Booker T and the MGs', title: 'Green onions (Intro)' },
        { artist: 'Booker T and the MGs', title: 'Green onions (Intro DJ 1)' },
        { artist: 'Booker T and the MGs', title: 'Green onions (Intro DJ 2)' },
        { artist: 'Booker T and the MGs', title: 'Green onions (Outro)' },
        { artist: 'Booker T and the MGs', title: 'Green onions (Outro DJ 1)' },
        { artist: 'Booker T and the MGs', title: 'Green onions (Outro DJ 2)' },
        { artist: 'Maceo and the Macks', title: 'Cross the tracks (we better go back)' },
        { artist: 'Maceo and the Macks', title: 'Cross the tracks (we better go back) (Intro)' },
        { artist: 'Maceo and the Macks', title: 'Cross the tracks (we better go back) (Intro DJ 1)' },
        { artist: 'Maceo and the Macks', title: 'Cross the tracks (we better go back) (Intro DJ 2)' },
        { artist: 'Maceo and the Macks', title: 'Cross the tracks (we better go back) (Outro)' },
        { artist: 'Maceo and the Macks', title: 'Cross the tracks (we better go back) (Outro DJ 1)' },
        { artist: 'Maceo and the Macks', title: 'Cross the tracks (we better go back) (Outro DJ 2)' },
        { artist: 'Bobby Byrd', title: 'Hot pants' },
        { artist: 'Bobby Byrd', title: 'Hot pants (Intro)' },
        { artist: 'Bobby Byrd', title: 'Hot pants (Intro DJ 1)' },
        { artist: 'Bobby Byrd', title: 'Hot pants (Intro DJ 2)' },
        { artist: 'Bobby Byrd', title: 'Hot pants (Outro)' },
        { artist: 'Bobby Byrd', title: 'Hot pants (Outro DJ 1)' },
        { artist: 'Bobby Byrd', title: 'Hot pants (Outro DJ 2)' },
        { artist: 'Lyn Collins', title: 'Think about it' },
        { artist: 'Lyn Collins', title: 'Think about it (Intro)' },
        { artist: 'Lyn Collins', title: 'Think about it (Intro DJ 1)' },
        { artist: 'Lyn Collins', title: 'Think about it (Intro DJ 2)' },
        { artist: 'Lyn Collins', title: 'Think about it (Outro)' },
        { artist: 'Lyn Collins', title: 'Think about it (Outro DJ 1)' },
        { artist: 'Lyn Collins', title: 'Think about it (Outro DJ 2)' },
        { artist: 'The blackbyrds', title: 'Rock creek park' },
        { artist: 'The blackbyrds', title: 'Rock creek park (Intro)' },
        { artist: 'The blackbyrds', title: 'Rock creek park (Intro DJ 1)' },
        { artist: 'The blackbyrds', title: 'Rock creek park (Intro DJ 2)' },
        { artist: 'The blackbyrds', title: 'Rock creek park (Outro)' },
        { artist: 'The blackbyrds', title: 'Rock creek park (Outro DJ 1)' },
        { artist: 'The blackbyrds', title: 'Rock creek park (Outro DJ 2)' },
        { artist: 'Bob James', title: 'Nautilus' },
        { artist: 'Bob James', title: 'Nautilus (Intro)' },
        { artist: 'Bob James', title: 'Nautilus (Intro DJ 1)' },
        { artist: 'Bob James', title: 'Nautilus (Intro DJ 2)' },
        { artist: 'Bob James', title: 'Nautilus (Outro)' },
        { artist: 'Bob James', title: 'Nautilus (Outro DJ 1)' },
        { artist: 'James Brown', title: 'Funky president' },
        { artist: 'James Brown', title: 'Funky president (Intro)' },
        { artist: 'James Brown', title: 'Funky president (Intro DJ 1)' },
        { artist: 'James Brown', title: 'Funky president (Intro DJ 2)' },
        { artist: 'James Brown', title: 'Funky president (Outro)' },
        { artist: 'James Brown', title: 'Funky president (Outro DJ 1)' },
        { artist: 'James Brown', title: 'Funky president (Outro DJ 2)' },
        { artist: 'The JBs', title: 'Grunt' },
        { artist: 'The JBs', title: 'Grunt (Intro)' },
        { artist: 'The JBs', title: 'Grunt (Intro DJ 1)' },
        { artist: 'The JBs', title: 'Grunt (Intro DJ 2)' },
        { artist: 'The JBs', title: 'Grunt (Outro)' },
        { artist: 'The JBs', title: 'Grunt (Outro DJ 1)' },
        { artist: 'The JBs', title: 'Grunt (Outro DJ 2)' },
        { artist: 'The chakachas', title: 'Jungle fever' },
        { artist: 'The chakachas', title: 'Jungle fever (Intro)' },
        { artist: 'The chakachas', title: 'Jungle fever (Intro DJ 1)' },
        { artist: 'The chakachas', title: 'Jungle fever (Intro DJ 2)' },
        { artist: 'The chakachas', title: 'Jungle fever (Outro)' },
        { artist: 'The chakachas', title: 'Jungle fever (Outro DJ 1)' },
        { artist: 'The chakachas', title: 'Jungle fever (Outro DJ 2)' },
        { artist: 'War', title: 'Low rider' },
        { artist: 'War', title: 'Low rider (Intro)' },
        { artist: 'War', title: 'Low rider (Intro DJ 1)' },
        { artist: 'War', title: 'Low rider (Intro DJ 2)' },
        { artist: 'War', title: 'Low rider (Outro)' },
        { artist: 'War', title: 'Low rider (Outro DJ 1)' },
        { artist: 'War', title: 'Low rider (Outro DJ 2)' },
        { artist: 'Maceo and the Macks', title: 'Soul power 74' },
        { artist: 'Maceo and the Macks', title: 'Soul power 74 (Intro)' },
        { artist: 'Maceo and the Macks', title: 'Soul power 74 (Intro DJ 1)' },
        { artist: 'Maceo and the Macks', title: 'Soul power 74 (Outro)' },
        { artist: 'Maceo and the Macks', title: 'Soul power 74 (Outro DJ 1)' },
        { artist: 'Gloria Jones', title: 'Tainted love' },
        { artist: 'Gloria Jones', title: 'Tainted love (Intro)' },
        { artist: 'Gloria Jones', title: 'Tainted love (Outro)' },
        { artist: 'Sir Joe Quarterman and Free soul', title: '(I got) so much trouble in my mind' },
        { artist: 'Sir Joe Quarterman and Free soul', title: '(I got) so much trouble in my mind (Intro)' },
        { artist: 'Sir Joe Quarterman and Free soul', title: '(I got) so much trouble in my mind (Intro DJ 1)' },
        { artist: 'Sir Joe Quarterman and Free soul', title: '(I got) so much trouble in my mind (Intro DJ 2)' },
        { artist: 'Sir Joe Quarterman and Free soul', title: '(I got) so much trouble in my mind (Outro)' },
        { artist: 'Sir Joe Quarterman and Free soul', title: '(I got) so much trouble in my mind (Outro DJ 1)' },
        { artist: 'Lyn Collins', title: 'Rock me again and again' },
        { artist: 'Lyn Collins', title: 'Rock me again and again (Intro)' },
        { artist: 'Lyn Collins', title: 'Rock me again and again (Intro DJ 1)' },
        { artist: 'Lyn Collins', title: 'Rock me again and again (Intro DJ 2)' },
        { artist: 'Lyn Collins', title: 'Rock me again and again (Outro)' },
        { artist: 'Lyn Collins', title: 'Rock me again and again (Outro DJ 1)' },
        { artist: 'Lyn Collins', title: 'Rock me again and again (Outro DJ 2)' },
        { artist: 'Bobby Byrd', title: 'I know you got soul' },
        { artist: 'Bobby Byrd', title: 'I know you got soul (Intro)' },
        { artist: 'Bobby Byrd', title: 'I know you got soul (Intro DJ 1)' },
        { artist: 'Bobby Byrd', title: 'I know you got soul (Intro DJ 2)' },
        { artist: 'Bobby Byrd', title: 'I know you got soul (Outro)' },
        { artist: 'Bobby Byrd', title: 'I know you got soul (Outro DJ 1)' },
        { artist: 'James Brown', title: 'The payback' },
        { artist: 'James Brown', title: 'The payback (Intro)' },
        { artist: 'James Brown', title: 'The payback (Intro DJ 1)' },
        { artist: 'James Brown', title: 'The payback (Intro DJ 2)' },
        { artist: 'James Brown', title: 'The payback (Outro)' },
        { artist: 'Harlem underground band', title: "Smokin' cheeba cheeba" },
        { artist: 'Harlem underground band', title: "Smokin' cheeba cheeba (Intro)" },
        { artist: 'Harlem underground band', title: "Smokin' cheeba cheeba (Intro DJ 1)" },
        { artist: 'Harlem underground band', title: "Smokin' cheeba cheeba (Intro DJ 2)" },
        { artist: 'Harlem underground band', title: "Smokin' cheeba cheeba (Outro)" },
        { artist: 'Harlem underground band', title: "Smokin' cheeba cheeba (Outro DJ 1)" },
        { artist: 'Harlem underground band', title: "Smokin' cheeba cheeba (Outro DJ 2)" },
    ],
};
