import { Station } from '../stations';

export const WCTR: Station = {
    title: 'WCTR',
    hash: 'cda6d4299457eff44b33a7f1cb1d2a72',
    tracks: [
        { title: 'People dying... and explosions' },
        { title: 'Sensationalist bullshit' },
        { title: 'At home, at work, or in rehab' },
        { title: 'If you crave news' },
        { title: 'Opinions are free' },
        { title: 'Talk is cheap' },
        { title: 'Deal with your ignorance' },
        { title: 'All the news' },
        { artist: 'Bob Sevra', title: 'Area 53 - 1' },
        { artist: 'Bob Sevra', title: 'Area 53 - 1 (Intro)' },
        { artist: 'Bob Sevra', title: 'Area 53 - 1 (Outro)' },
        { artist: 'Bob Sevra', title: 'Area 53 - 2' },
        { artist: 'Bob Sevra', title: 'Area 53 - 2 (Intro)' },
        { artist: 'Bob Sevra', title: 'Area 53 - 2 (Outro)' },
        { artist: 'Bob Sevra', title: 'Area 53 - 3' },
        { artist: 'Bob Sevra', title: 'Area 53 - 3 (Intro)' },
        { artist: 'Bob Sevra', title: 'Area 53 - 3 (Outro)' },
        { artist: 'Peter Marx', title: 'Entertaining America - 1' },
        { artist: 'Peter Marx', title: 'Entertaining America - 1 (Intro)' },
        { artist: 'Peter Marx', title: 'Entertaining America - 1 (Outro)' },
        { artist: 'Lazlow', title: 'Entertaining America - 2' },
        { artist: 'Lazlow', title: 'Entertaining America - 2 (Intro)' },
        { artist: 'Lazlow', title: 'Entertaining America - 2 (Outro)' },
        { artist: 'Lazlow', title: 'Entertaining America - 3' },
        { artist: 'Lazlow', title: 'Entertaining America - 3 (Intro)' },
        { artist: 'Lazlow', title: 'Entertaining America - 3 (Outro)' },
        { artist: 'Lazlow', title: 'Entertaining America - Teaser' },
        { artist: 'Lazlow', title: 'Entertaining America - Teaser (Intro)' },
        { artist: 'Lazlow', title: 'Entertaining America - Teaser (Outro)' },
        { artist: 'Paul Ames and Jackie Hoffman', title: 'I say - you say - 1' },
        { artist: 'Paul Ames and Jackie Hoffman', title: 'I say - you say - 1 (Intro)' },
        { artist: 'Paul Ames and Jackie Hoffman', title: 'I say - you say - 1 (Outro)' },
        { artist: 'Paul Ames and Jackie Hoffman', title: 'I say - you say - 2' },
        { artist: 'Paul Ames and Jackie Hoffman', title: 'I say - you say - 2 (Intro)' },
        { artist: 'Paul Ames and Jackie Hoffman', title: 'I say - you say - 2 (Outro)' },
        { artist: 'Sara Moon', title: 'Lonely hearts - 1' },
        { artist: 'Sara Moon', title: 'Lonely hearts - 1 (Intro)' },
        { artist: 'Sara Moon', title: 'Lonely hearts - 1 (Outro)' },
        { artist: 'Sara Moon', title: 'Lonely hearts - 2' },
        { artist: 'Sara Moon', title: 'Lonely hearts - 2 (Intro)' },
        { artist: 'Sara Moon', title: 'Lonely hearts - 2 (Outro)' },
        { artist: 'Sara Moon', title: 'Lonely hearts - 3' },
        { artist: 'Sara Moon', title: 'Lonely hearts - 3 (Intro)' },
        { artist: 'Sara Moon', title: 'Lonely hearts - 3 (Outro)' },
        { artist: 'Andy Dick', title: 'Gardening with Maurice - Teaser 1' },
        { artist: 'Andy Dick', title: 'Gardening with Maurice - Teaser 1 (Intro)' },
        { artist: 'Andy Dick', title: 'Gardening with Maurice - Teaser 1 (Outro)' },
        { artist: 'Andy Dick', title: 'Gardening with Maurice - Teaser 2' },
        { artist: 'Andy Dick', title: 'Gardening with Maurice - Teaser 2 (Intro)' },
        { artist: 'Andy Dick', title: 'Gardening with Maurice - Teaser 2 (Outro)' },
        { artist: 'Andy Dick', title: 'Gardening with Maurice - 1' },
        { artist: 'Andy Dick', title: 'Gardening with Maurice - 1 (Intro)' },
        { artist: 'Andy Dick', title: 'Gardening with Maurice - 1 (Outro)' },
        { artist: 'Andy Dick', title: 'Gardening with Maurice - 2' },
        { artist: 'Andy Dick', title: 'Gardening with Maurice - 2 (Intro)' },
        { artist: 'Andy Dick', title: 'Gardening with Maurice - 2 (Outro)' },
        { artist: 'Sharon Washington and Wil Wheaton', title: 'News - 1' },
        { artist: 'Sharon Washington and Wil Wheaton', title: 'News - 1 (Intro)' },
        { artist: 'Sharon Washington and Wil Wheaton', title: 'News - 1 (Outro)' },
        { artist: 'Sharon Washington and Wil Wheaton', title: 'News - 2' },
        { artist: 'Sharon Washington and Wil Wheaton', title: 'News - 2 (Intro)' },
        { artist: 'Sharon Washington and Wil Wheaton', title: 'News - 2 (Outro)' },
        { artist: 'Sharon Washington and Wil Wheaton', title: 'News - 3' },
        { artist: 'Sharon Washington and Wil Wheaton', title: 'News - 3 (Intro)' },
        { artist: 'Sharon Washington and Wil Wheaton', title: 'News - 3 (Outro)' },
        { artist: 'Sharon Washington and Wil Wheaton', title: 'News - 4' },
        { artist: 'Sharon Washington and Wil Wheaton', title: 'News - 4 (Intro)' },
        { artist: 'Sharon Washington and Wil Wheaton', title: 'News - 4 (Outro)' },
        { artist: 'Sharon Washington and Wil Wheaton', title: 'News - 5' },
        { artist: 'Sharon Washington and Wil Wheaton', title: 'News - 5 (Intro)' },
        { artist: 'Sharon Washington and Wil Wheaton', title: 'News - 5 (Outro)' },
        { artist: 'Sharon Washington and Wil Wheaton', title: 'News - 6' },
        { artist: 'Sharon Washington and Wil Wheaton', title: 'News - 6 (Intro)' },
        { artist: 'Sharon Washington and Wil Wheaton', title: 'News - 6 (Outro)' },
        { artist: 'Sharon Washington and Wil Wheaton', title: 'News - 7' },
        { artist: 'Sharon Washington and Wil Wheaton', title: 'News - 7 (Intro)' },
        { artist: 'Sharon Washington and Wil Wheaton', title: 'News - 7 (Outro)' },
        { artist: 'Sharon Washington and Wil Wheaton', title: 'News - 8' },
        { artist: 'Sharon Washington and Wil Wheaton', title: 'News - 8 (Intro)' },
        { artist: 'Sharon Washington and Wil Wheaton', title: 'News - 8 (Outro)' },
        { artist: 'Sharon Washington and Wil Wheaton', title: 'News - 9' },
        { artist: 'Sharon Washington and Wil Wheaton', title: 'News - 9 (Intro)' },
        { artist: 'Sharon Washington and Wil Wheaton', title: 'News - 9 (Outro)' },
        { artist: 'Sharon Washington and Wil Wheaton', title: 'News - 10' },
        { artist: 'Sharon Washington and Wil Wheaton', title: 'News - 10 (Intro)' },
        { artist: 'Sharon Washington and Wil Wheaton', title: 'News - 10 (Outro)' },
        { artist: 'Sharon Washington and Wil Wheaton', title: 'News - 11' },
        { artist: 'Sharon Washington and Wil Wheaton', title: 'News - 11 (Intro)' },
        { artist: 'Sharon Washington and Wil Wheaton', title: 'News - 11 (Outro)' },
        { artist: 'Peter Apel', title: 'The tight end zone - 1' },
        { artist: 'Peter Apel', title: 'The tight end zone - 1 (Intro)' },
        { artist: 'Peter Apel', title: 'The tight end zone - 1 (Outro)' },
        { artist: 'Peter Apel', title: 'The tight end zone - 2' },
        { artist: 'Peter Apel', title: 'The tight end zone - 2 (Intro)' },
        { artist: 'Peter Apel', title: 'The tight end zone - 2 (Outro)' },
        { artist: 'Sam Tsoutsouvas', title: 'The wild traveler - 1' },
        { artist: 'Sam Tsoutsouvas', title: 'The wild traveler - 1 (Intro)' },
        { artist: 'Sam Tsoutsouvas', title: 'The wild traveler - 1 (Outro)' },
        { artist: 'Sam Tsoutsouvas', title: 'The wild traveler - 2' },
        { artist: 'Sam Tsoutsouvas', title: 'The wild traveler - 2 (Intro)' },
        { artist: 'Sam Tsoutsouvas', title: 'The wild traveler - 2 (Outro)' },
    ],
};
